CREATE TABLE IF NOT EXISTS schema_migrations (id text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE organizations (id text PRIMARY KEY, name text NOT NULL, slug text UNIQUE NOT NULL, status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','blocked')), source text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id text PRIMARY KEY, email text UNIQUE NOT NULL, password_hash text NOT NULL, role text NOT NULL CHECK(role IN ('owner','staff','partner')), permissions text[] NOT NULL DEFAULT '{}', active boolean NOT NULL DEFAULT true, mfa_secret text, mfa_enabled boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE memberships (user_id text REFERENCES users ON DELETE CASCADE, organization_id text REFERENCES organizations, PRIMARY KEY(user_id,organization_id));
CREATE TABLE sessions (token_hash text PRIMARY KEY, user_id text REFERENCES users ON DELETE CASCADE, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE invitations (token_hash text PRIMARY KEY, email text NOT NULL, role text NOT NULL CHECK(role IN ('staff','partner')), organization_id text REFERENCES organizations, permissions text[] DEFAULT '{}', expires_at timestamptz NOT NULL, used_at timestamptz);
CREATE TABLE recovery_tokens (token_hash text PRIMARY KEY, user_id text REFERENCES users, expires_at timestamptz NOT NULL, used_at timestamptz);
CREATE TABLE destinations (id text PRIMARY KEY, names jsonb NOT NULL, aliases text[] NOT NULL DEFAULT '{}', timezone text NOT NULL DEFAULT 'Asia/Ho_Chi_Minh');
CREATE TABLE categories (id text PRIMARY KEY, names jsonb NOT NULL, slug text UNIQUE NOT NULL, parent_id text REFERENCES categories, sort_order integer NOT NULL DEFAULT 0, icon text, active boolean NOT NULL DEFAULT true);
CREATE TABLE offerings (id text PRIMARY KEY, organization_id text REFERENCES organizations NOT NULL, type text NOT NULL CHECK(type IN ('tour','activity','rental')), category_id text REFERENCES categories NOT NULL, destination_id text REFERENCES destinations, slug text UNIQUE NOT NULL, status text NOT NULL CHECK(status IN ('draft','review','published','correction','suspended','archive')), version integer NOT NULL DEFAULT 1, published_data jsonb, working_data jsonb NOT NULL, source_id text UNIQUE, source_hash text, editor_modified boolean NOT NULL DEFAULT false, updated_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz);
CREATE TABLE revisions (id text PRIMARY KEY, offering_id text REFERENCES offerings NOT NULL, version integer NOT NULL, author_id text REFERENCES users, state text NOT NULL, data jsonb NOT NULL, note text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(offering_id,version));
CREATE TABLE media (id text PRIMARY KEY, offering_id text REFERENCES offerings, organization_id text REFERENCES organizations NOT NULL, path text NOT NULL, sha256 text NOT NULL, mime text NOT NULL, width integer, height integer, alt jsonb NOT NULL DEFAULT '{}', caption jsonb NOT NULL DEFAULT '{}', rights text, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE url_registry (path text PRIMARY KEY CHECK(path LIKE '/%'), locale text NOT NULL CHECK(locale IN ('ru','en')), kind text NOT NULL CHECK(kind IN ('page','offering','redirect','gone')), offering_id text REFERENCES offerings, target text, source_status integer, source_file text, UNIQUE(path,locale));
CREATE TABLE import_runs (id text PRIMARY KEY, source text NOT NULL, dry_run boolean NOT NULL, summary jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE import_rows (id text PRIMARY KEY, run_id text REFERENCES import_runs NOT NULL, source_id text NOT NULL, source_hash text NOT NULL, source_file text NOT NULL, source_sheet text, raw_data jsonb NOT NULL, parsed_data jsonb, outcome text NOT NULL, error text, obtained_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE conflicts (id text PRIMARY KEY, offering_id text REFERENCES offerings, source_id text NOT NULL, field text NOT NULL, detail jsonb NOT NULL, status text NOT NULL DEFAULT 'unresolved', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(source_id,field));
CREATE TABLE audit_log (id text PRIMARY KEY, user_id text REFERENCES users, action text NOT NULL, entity text NOT NULL, entity_id text, detail jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE leads (id text PRIMARY KEY, idempotency_key text UNIQUE NOT NULL, request_hash text NOT NULL, offering_id text REFERENCES offerings NOT NULL, organization_id text REFERENCES organizations NOT NULL, locale text NOT NULL, status text NOT NULL DEFAULT 'new' CHECK(status IN ('new','in_progress','waiting','confirmed','completed','cancelled','spam')), assigned_to text REFERENCES users, contact jsonb NOT NULL, request jsonb NOT NULL, snapshot jsonb NOT NULL, source_path text NOT NULL, utm jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE lead_events (id text PRIMARY KEY, lead_id text REFERENCES leads NOT NULL, user_id text REFERENCES users, action text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE outbox (id text PRIMARY KEY, lead_id text REFERENCES leads NOT NULL, channel text NOT NULL CHECK(channel IN ('email','telegram')), status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','sent','retry','blocked')), attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), lease_until timestamptz, provider_id text, last_error text, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(lead_id,channel));
CREATE TABLE rate_limits (key text PRIMARY KEY, count integer NOT NULL, reset_at timestamptz NOT NULL);

CREATE ROLE enduro_app NOLOGIN;
GRANT USAGE ON SCHEMA public TO enduro_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON offerings,revisions,media,leads,lead_events,organizations,memberships,categories,destinations,url_registry,conflicts,audit_log TO enduro_app;
CREATE FUNCTION app_uid() RETURNS text LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('app.user_id',true),'') $$;
CREATE FUNCTION app_role() RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT role FROM users WHERE id=app_uid() AND active $$;
CREATE FUNCTION app_permission(p text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT coalesce((SELECT role='owner' OR (role='staff' AND p=ANY(permissions)) FROM users WHERE id=app_uid() AND active),false) $$;
CREATE FUNCTION app_org(o text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM memberships m JOIN organizations g ON g.id=m.organization_id JOIN users u ON u.id=m.user_id WHERE m.user_id=app_uid() AND m.organization_id=o AND g.status='active' AND u.active) $$;
ALTER TABLE offerings ENABLE ROW LEVEL SECURITY;
CREATE POLICY offerings_read ON offerings FOR SELECT TO enduro_app USING(app_permission('catalog') OR app_org(organization_id));
CREATE POLICY offerings_create ON offerings FOR INSERT TO enduro_app WITH CHECK(app_permission('catalog') OR (app_org(organization_id) AND status='draft' AND published_data IS NULL));
CREATE POLICY offerings_edit ON offerings FOR UPDATE TO enduro_app USING(app_permission('catalog') OR app_org(organization_id)) WITH CHECK(app_permission('catalog') OR app_org(organization_id));
CREATE POLICY offerings_delete ON offerings FOR DELETE TO enduro_app USING(app_permission('catalog'));
CREATE FUNCTION guard_publication() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF current_user='enduro_app' AND NOT app_permission('publish') AND (NEW.published_data IS DISTINCT FROM OLD.published_data OR NEW.status IN ('published','suspended','archive') AND NEW.status IS DISTINCT FROM OLD.status OR NEW.organization_id IS DISTINCT FROM OLD.organization_id) THEN RAISE EXCEPTION 'Publication permission required'; END IF; RETURN NEW; END $$;
CREATE TRIGGER offerings_publication BEFORE UPDATE ON offerings FOR EACH ROW EXECUTE FUNCTION guard_publication();
ALTER TABLE revisions ENABLE ROW LEVEL SECURITY;
CREATE POLICY revision_access ON revisions TO enduro_app USING(EXISTS(SELECT 1 FROM offerings o WHERE o.id=offering_id)) WITH CHECK(EXISTS(SELECT 1 FROM offerings o WHERE o.id=offering_id));
ALTER TABLE media ENABLE ROW LEVEL SECURITY;
CREATE POLICY media_access ON media TO enduro_app USING(app_permission('catalog') OR app_org(organization_id)) WITH CHECK(app_permission('catalog') OR app_org(organization_id));
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY leads_access ON leads TO enduro_app USING(app_permission('leads') OR (app_role()='staff' AND assigned_to=app_uid())) WITH CHECK(app_permission('leads'));
ALTER TABLE lead_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY lead_events_access ON lead_events TO enduro_app USING(EXISTS(SELECT 1 FROM leads l WHERE l.id=lead_id)) WITH CHECK(EXISTS(SELECT 1 FROM leads l WHERE l.id=lead_id));
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
CREATE POLICY org_read ON organizations FOR SELECT TO enduro_app USING(app_permission('users') OR app_org(id));
CREATE POLICY org_write ON organizations FOR ALL TO enduro_app USING(app_permission('users')) WITH CHECK(app_permission('users'));
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY memberships_access ON memberships TO enduro_app USING(app_permission('users') OR user_id=app_uid()) WITH CHECK(app_permission('users'));
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY audit_read ON audit_log FOR SELECT TO enduro_app USING(app_permission('users'));
CREATE POLICY audit_insert ON audit_log FOR INSERT TO enduro_app WITH CHECK(user_id=app_uid());
ALTER TABLE conflicts ENABLE ROW LEVEL SECURITY;
CREATE POLICY conflict_access ON conflicts TO enduro_app USING(app_permission('catalog')) WITH CHECK(app_permission('catalog'));
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY category_read ON categories FOR SELECT TO enduro_app USING(true);
CREATE POLICY category_write ON categories FOR ALL TO enduro_app USING(app_permission('catalog')) WITH CHECK(app_permission('catalog'));
ALTER TABLE destinations ENABLE ROW LEVEL SECURITY;
CREATE POLICY destination_read ON destinations FOR SELECT TO enduro_app USING(true);
CREATE POLICY destination_write ON destinations FOR ALL TO enduro_app USING(app_permission('catalog')) WITH CHECK(app_permission('catalog'));
ALTER TABLE url_registry ENABLE ROW LEVEL SECURITY;
CREATE POLICY url_read ON url_registry FOR SELECT TO enduro_app USING(app_permission('urls'));
CREATE POLICY url_write ON url_registry FOR ALL TO enduro_app USING(app_permission('urls')) WITH CHECK(app_permission('urls'));
