'use client';
import {useEffect} from 'react';
export function EnduroTourRuntime({id}:{id:string}){useEffect(()=>{
 const root=document.querySelector<HTMLElement>('.enduro-tour');if(!root)return;
 const abort=new AbortController(),signal=abort.signal,drawer=root.querySelector<HTMLElement>('#drawer')!,backdrop=root.querySelector<HTMLElement>('#backdrop')!,trigger=root.querySelector<HTMLElement>('#openMenu')!,header=root.querySelector<HTMLElement>('#siteHeader')!,toc=root.querySelector<HTMLElement>('#sideToc')!;
 const previous=document.body.style.overflow;let timer:ReturnType<typeof setTimeout>;
 const menu=(open:boolean,restore=true)=>{clearTimeout(timer);drawer.classList.toggle('open',open);backdrop.classList.toggle('open',open);drawer.inert=!open;drawer.setAttribute('aria-hidden',String(!open));trigger.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':previous;if(open)timer=setTimeout(()=>drawer.querySelector<HTMLElement>('#closeMenu')?.focus({preventScroll:true}),Math.max(...getComputedStyle(drawer).transitionDuration.split(',').map(v=>parseFloat(v)*1000))+50);else if(restore)trigger.focus({preventScroll:true});};
 trigger.addEventListener('click',()=>menu(true),{signal});root.querySelector('#closeMenu')!.addEventListener('click',()=>menu(false),{signal});backdrop.addEventListener('click',()=>menu(false),{signal});drawer.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu(false,false),{signal}));
 document.addEventListener('keydown',e=>{if(!drawer.classList.contains('open'))return;if(e.key==='Escape'){e.preventDefault();menu(false);}if(e.key==='Tab'){const nodes=[...drawer.querySelectorAll<HTMLElement>('a[href],button')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}},{signal});
 const scroll=()=>{header.classList.toggle('scrolled',scrollY>50);header.classList.toggle('over-content',(root.querySelector('.hero')?.getBoundingClientRect().bottom??0)<74);toc.classList.toggle('show',scrollY>650);};window.addEventListener('scroll',scroll,{passive:true,signal});scroll();
 const links=[...toc.querySelectorAll<HTMLAnchorElement>('a')],observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)links.forEach(a=>{const active=a.hash==='#'+e.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});},{rootMargin:'-35% 0px -55% 0px'});links.forEach(a=>{const section=root.querySelector(a.hash);if(section)observer.observe(section);});root.dataset.tourReady='true';
 return()=>{clearTimeout(timer);abort.abort();observer.disconnect();document.body.style.overflow=previous;delete root.dataset.tourReady;};
 },[id]);return null;}
