import Link from 'next/link';
import {readFileSync} from 'node:fs';
import type {Offering} from '@/lib/catalog-types';
import {duration,price,publicOfferings} from '@/lib/catalog';
import {cityPages,cityHref} from '@/lib/city-pages';
import {isEnduroTour,tourContent} from '@/lib/enduro-tours';
import {getExportedPage} from '@/lib/exported-content';
import contacts from '@/content/homepage-ru/contacts.json';
import assets from '@/content/assets.json';
import tourMedia from '@/content/enduro-tours/media.json';
import {LeadForm} from '@/components/catalog/LeadForm';
import {EnduroTourRuntime} from './EnduroTourRuntime';
const sections=[['flow','Как проходит'],['route','Трасса'],['equipment','Экипировка'],['bikes','Мотоциклы'],['guides','Гиды'],['included','Условия'],['gallery','Фото'],['price','Цена'],['faq','Вопросы']] as const;
function Head({kicker,title,copy}:{kicker:string;title:string;copy?:string}){return <div className="head"><div><div className="eyebrow">{kicker}</div><h2>{title}</h2></div>{copy&&<p>{copy}</p>}</div>;}
function Photo({src,alt,eager=false}:{src:string;alt:string;eager?:boolean}){const m=(tourMedia as Record<string,{avif:string;webp:string;width:number;height:number}>)[src];return m?<picture><source srcSet={m.avif} type="image/avif"/><img src={m.webp} width={m.width} height={m.height} alt={alt} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':'auto'} decoding="async"/></picture>:<img src={src} alt={alt} loading={eager?'eager':'lazy'} decoding="async"/>;}
const photoForModel=(model:string)=>{const normalized=model.toLowerCase().replace(/[^a-z0-9]/g,'');return Object.entries(assets).find(([url])=>{const file=url.split('/').at(-1)?.replace(/\.\w+$/,'').toLowerCase().replace(/[^a-z0-9]/g,'')??'';return file.length>4&&(normalized.includes(file)||file.includes(normalized));})?.[1];};
export async function EnduroTourDetail({offering:o,path}:{offering:Offering;path:string}){
 const d=o.published_data!,t=d.translations.ru!,c=cityPages[o.destination_id],content=tourContent(o),time=duration(d,'ru'),money=price(d.commerce,'ru'),photos=d.photos,hero=photos[0],related=(await publicOfferings('ru')).filter(x=>x.id!==o.id&&isEnduroTour(x)&&x.destination_id===o.destination_id).slice(0,3),end=d.endDestinationId?cityPages[d.endDestinationId]:null;
 const level=({easy:'Лёгкий уровень',medium:'Средний уровень',hard:'Сложный уровень'} as Record<string,string>)[d.level??'']??d.level;
 const existing=new Set(['siteHeader','drawer','openMenu','closeMenu','backdrop','sideToc','booking','request','other-tours',...sections.map(([s])=>s)]);
 const legacy=getExportedPage(path)?.anchors.filter(a=>!existing.has(a))??[];
 const faq=[['Как выбрать подходящий уровень?',level?`Уровень этого тура: ${level.toLowerCase()}. В заявке расскажите о своём опыте, чтобы организатор подтвердил подходящий маршрут и технику.`:'Опишите опыт в заявке. Организатор подтвердит требования и подходящий маршрут.'],['Какой мотоцикл мне дадут?','Конкретную модель и её стоимость подтверждаем вместе с датой. Укажите свой рост, опыт и пожелания в комментарии.'],['На каком языке проходит тур?',d.guideLanguages?.length?`В каталоге указаны: ${d.guideLanguages?.join(', ')}. Гид и язык подтверждаются для выбранной даты.`:'Укажите нужный язык в заявке. Состав гидов и язык сопровождения подтверждаются для вашей даты.'],['Что происходит при плохой погоде?','Состояние трассы, условия переноса и отмены обсуждаются с организатором до подтверждения поездки.'],['Заявка сразу подтверждает бронь?','Нет. Сначала мы проверяем дату, технику и состав группы, затем подтверждаем итоговую стоимость и условия.']];
 return <><style dangerouslySetInnerHTML={{__html:readFileSync('content/enduro-tours/styles.css','utf8')}}/><div className="enduro-tour" data-offering={o.id}>
 <header className="site-header" id="siteHeader"><div className="container header-inner"><Link prefetch={false} className="header-chip brand" href="/ru"><img src="/assets/homepage-ru/e0b769d07f70df9595cb.webp" width={158} height={85} alt="Enduro Vietnam"/></Link><nav className="nav" aria-label="Главная навигация"><Link prefetch={false} className="header-chip" href={cityHref(o.destination_id)}>{c?.name??'Город'}</Link><Link prefetch={false} className="header-chip" href="/ru/all-tours?q=эндуро">Эндуро</Link><Link prefetch={false} className="header-chip" href={'/ru/rentals/motorbikes?city='+o.destination_id}>Аренда</Link></nav><div className="head-actions"><a className="header-chip ig" href={contacts.instagram} target="_blank" rel="noopener noreferrer">Instagram</a><a className="header-chip wa" href={contacts.whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp</a><button className="header-chip menu" id="openMenu" type="button" aria-controls="drawer" aria-expanded="false">Меню</button></div></div></header>
 <div className="backdrop" id="backdrop"/><aside className="drawer" id="drawer" role="dialog" aria-modal="true" aria-label="Меню тура" aria-hidden="true" inert><div className="container drawer-inner"><div className="drawer-top"><Link className="brand" href="/ru" prefetch={false}><img src="/assets/homepage-ru/e0b769d07f70df9595cb.webp" width={158} height={85} alt="Enduro Vietnam"/></Link><button className="btn btn-dark" id="closeMenu" type="button">Закрыть ×</button></div><div className="drawer-grid"><div><h3>{c?.name}</h3><div className="drawer-links"><Link href={cityHref(o.destination_id)} prefetch={false}>Страница города</Link><Link href={'/ru/all-tours?city='+o.destination_id} prefetch={false}>Все туры</Link><Link href={'/ru/rentals/motorbikes?city='+o.destination_id} prefetch={false}>Аренда</Link>{d.routes.en&&<Link href={d.routes.en} prefetch={false} lang="en">English</Link>}</div></div><div><h3>Разделы тура</h3><div className="drawer-links">{sections.map(([id,label])=><a key={id} href={'#'+id}>{label}</a>)}</div></div><div className="drawer-cta"><h3>Нужна помощь?</h3><p>Подберём формат поездки и уточним технику на вашу дату.</p><a className="btn btn-orange" href="#booking">Запросить дату →</a></div></div></div></aside>
 <nav className="side-toc" id="sideToc" aria-label="Разделы тура"><small>Этот тур</small>{sections.map(([id,label])=><a key={id} href={'#'+id}>{label}</a>)}</nav>
 <main><section className="hero"><div className="hero-media">{hero&&<Photo src={hero.src} alt={hero.alt.ru||t.title} eager/>}</div><div className="container hero-inner"><div className="hero-copy"><div className="crumbs"><Link prefetch={false} href="/ru">Главная</Link><span>→</span><Link prefetch={false} href={cityHref(o.destination_id)}>{c?.name}</Link><span>→</span><span>{time}</span></div><h1>{t.title} — {time}</h1><p className="subtitle">{t.description}</p><div className="hero-facts"><span>{time}</span>{level&&<span>{level}</span>}{d.groupSize&&<span>Группа: {d.groupSize} чел.</span>}{end&&<span>{c?.name} → {end.name}</span>}{!!d.guideLanguages?.length&&<span>{d.guideLanguages?.join(' / ')}</span>}</div><div className="hero-buy"><div className="hero-price"><small>Стоимость тура</small>{money}</div><a className="btn btn-orange" href="#booking">Запросить дату →</a></div></div></div></section>
 <section className="quick-index"><div className="container quick-row"><div className="quick-label">Всё о туре</div><div className="quick-scroll">{sections.filter(([id])=>['flow','route','equipment','bikes','guides','price'].includes(id)).map(([id,label],i)=><a key={id} className="quick-pill" href={'#'+id}><span className="quick-thumb">{photos[i%photos.length]&&<Photo src={photos[i%photos.length].src} alt=""/>}</span>{label}</a>)}</div></div></section>
 <section className="section screenish" id="flow"><div className="container"><Head kicker="Программа" title="Как проходит выезд" copy={`Формат: ${time}. Программа и условия относятся к выбранному туру.`}/><div className="timeline">{(content.steps.length?content.steps:[{title:'Запрос даты',text:'Укажите дату, количество участников и опыт.'},{title:'Подтверждение программы',text:'Согласуем маршрут, технику и условия поездки.'},{title:'Подготовка к старту',text:'Организатор сообщит точку встречи и требования.'},{title:'Поездка',text:'Следуем согласованной программе с остановками на маршруте.'}]).map((s,i)=><article className="step" key={i}><div className="step-no">0{i+1}</div><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></div></section>
 <section className="section pine screenish" id="route"><div className="container"><Head kicker="Маршрут" title={end?`${c?.name} → ${end.name}`:`Эндуро ${c?.inName??''}`} copy={content.overview}/><div className="trail-layout"><div className="trail-media">{photos[1]&&<Photo src={photos[1].src} alt={photos[1].alt.ru||t.title}/>}<div className="trail-caption"><strong>{c?.name}{end?' → '+end.name:''}</strong><span>{time}</span></div></div><div className="trail-summary"><div className="trail-item"><b>Длительность</b><span>{time}</span></div>{level&&<div className="trail-item"><b>Уровень</b><span>{level}</span></div>}{d.groupSize&&<div className="trail-item"><b>Размер группы</b><span>{d.groupSize} чел.</span></div>}<div className="trail-item"><b>Старт</b><span>{c?.name}. Место и время подтверждаются при бронировании.</span></div>{end&&<div className="trail-item"><b>Финиш</b><span>{end.name}</span></div>}</div></div>{typeof d.program?.ru==='string'&&<p>{d.program.ru}</p>}</div></section>
 <section className="section soft screenish" id="equipment"><div className="container"><Head kicker="Защита" title="Экипировка перед выездом" copy="Укажите рост, размеры и имеющуюся защиту в заявке. Точный комплект и наличие нужных размеров подтвердит организатор."/><div className="equipment-grid">{[['Шлем','Подбор размера и посадки перед стартом.'],['Защита','Уточните состав комплекта и условия выдачи.'],['Обувь','Размеры и доступность мотобот нужно подтвердить заранее.'],['Одежда и вода','Подскажем, что взять с собой для выбранного маршрута.']].map(([title,copy],i)=><article className="gear" key={title}><div className="gear-visual">{photos[i%photos.length]&&<Photo src={photos[i%photos.length].src} alt="Участники и техника на маршруте"/>}</div><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
 <section className="section screenish" id="bikes"><div className="container"><Head kicker="Техника" title="На чём поедем" copy="Модели из описания организатора. Наличие, комплектацию и стоимость выбранного байка подтверждаем на вашу дату."/><div className="bike-grid">{(d.variants.length?d.variants.map(v=>({name:v.name.ru??v.id,src:photoForModel(v.name.ru??''),cost:price(v.commerce,'ru')})):content.models.map(name=>({name,src:photoForModel(name),cost:'По наличию'}))).map((bike,i)=><article className="bike-card" key={bike.name}><div className="bike-img">{(bike.src??photos[i%photos.length]?.src)&&<Photo src={bike.src??photos[i%photos.length].src} alt={bike.src?bike.name:'Техника на маршруте; конкретную модель уточняем'}/>}</div><div className="bike-body"><div className="bike-kicker">Техника организатора</div><h3>{bike.name}</h3><p>Подбор под опыт и рост участника.</p><div className="bike-meta"><span>Подтверждаем на дату</span><span>{bike.cost}</span></div></div></article>)}</div><div className="bike-note"><strong>Подберём подходящий байк</strong><span>Напишите о своём опыте и пожеланиях. Если модель ещё не указана, согласуем её вместе с условиями поездки.</span><a className="btn btn-dark" href="#booking">Подобрать байк →</a></div></div></section>
 <section className="section soft screenish" id="guides"><div className="container"><Head kicker="Сопровождение" title="Гид на вашем маршруте" copy="Состав команды и язык сопровождения подтверждаем вместе с датой поездки."/><div className="guides-grid"><article className="guide-card"><div className="guide-photo">{photos[2]&&<Photo src={photos[2].src} alt="Участники тура на маршруте"/>}</div><div className="guide-body"><small>Организатор</small><h3>{d.supplier}</h3><p>Укажите предпочтительный язык и свой опыт в заявке.</p><div className="guide-tags">{(d.guideLanguages?.length?d.guideLanguages:['Язык по согласованию']).map(l=><span key={l}>{l}</span>)}</div></div></article><article className="guide-card"><div className="guide-photo">{photos[3]&&<Photo src={photos[3].src} alt="Фотография из материалов этого тура"/>}</div><div className="guide-body"><small>Перед поездкой</small><h3>Обсудим подготовку</h3><p>Уточните свой стаж, опыт бездорожья и ограничения. Конкретного гида и место старта сообщим при подтверждении.</p><a className="btn btn-ghost" href="#booking">Связаться с организатором</a></div></article></div></div></section>
 <section className="section screenish" id="included"><div className="container"><Head kicker="Условия" title="Что входит и что уточняется заранее" copy="Условия опубликованного описания. Итоговый состав пакета согласуется для выбранной даты и техники."/><div className="include-grid"><div className="include-card"><h3>В описании тура</h3><ul className="checklist">{(content.included.length?content.included:['Точный состав пакета уточняется при подтверждении.']).map((p,i)=><li key={i}>{p}</li>)}</ul></div><div className="include-card"><h3>Отдельно и по согласованию</h3><ul className="checklist no">{(content.excluded.length?content.excluded:['Трансфер и точка встречи','Страхование и ответственность за повреждения','Условия отмены и переноса']).map((p,i)=><li key={i}>{p}</li>)}</ul></div></div>{content.notes.length>0&&<details className="program-copy"><summary>Дополнительные условия организатора</summary>{content.notes.map((p,i)=><p key={i}>{p}</p>)}</details>}{typeof d.conditions?.ru==='string'&&<p>{d.conditions.ru}</p>}</div></section>
 <section className="section soft screenish" id="gallery"><div className="container"><Head kicker="Фотографии" title="Как выглядит этот тур" copy="Реальные фотографии из материалов этого предложения."/><div className="gallery-grid">{photos.slice(0,5).map((im,i)=><a key={im.src} className={'gallery-item'+(i===0?' big':'')} href={im.src} target="_blank" rel="noopener noreferrer" aria-label={'Открыть фото '+(i+1)}><Photo src={im.src} alt={im.alt.ru||t.title}/></a>)}</div>{photos.length>5&&<details className="program-copy"><summary>Все фотографии ({photos.length})</summary><div className="bike-grid">{photos.slice(5).map(im=><a href={im.src} key={im.src} target="_blank" rel="noopener noreferrer"><Photo src={im.src} alt={im.alt.ru||t.title}/></a>)}</div></details>}</div></section>
 <section className="section screenish" id="price"><div className="container price-panel"><div className="price-main"><div className="eyebrow" style={{color:'#fff'}}>Цена</div><h2>{t.title} · {time}</h2><p>Стоимость из опубликованного каталога. Итог подтверждается после выбора даты, мотоцикла и состава группы.</p><div className="price-box"><div><div className="big-price">{money}</div><div className="price-note">{d.commerce.unit?'Расчёт: '+d.commerce.unit:'Основание расчёта и комплектацию подтвердим при обращении.'}</div></div><a className="btn btn-white" href="#booking">Запросить дату →</a></div></div><div className="booking-info"><h3>Как подтверждается поездка</h3><ul><li>Вы отправляете желаемую дату и количество участников.</li><li>Организатор подтверждает гида и доступный байк.</li><li>Вы получаете актуальные условия и итоговую стоимость.</li><li>После согласования заявка становится бронью.</li></ul></div></div></section>
 <section className="section soft" id="faq"><div className="container faq-grid"><div className="head-copy"><div className="eyebrow">FAQ</div><h2 className="display" style={{fontSize:'clamp(32px,3.5vw,48px)',lineHeight:1}}>Вопросы о туре</h2><p>Длительность: {time}. Другие форматы смотрите на странице города.</p></div><div className="accordion">{faq.map(([q,a])=><details className="acc" key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
 <section className="section related" id="other-tours"><div className="container"><Head kicker={c?.name??'Другие туры'} title="Выберите другой формат эндуро"/><div className="related-grid">{related.map(r=>{const rd=r.published_data!,rt=rd.translations.ru!;return <Link prefetch={false} className="related-card" key={r.id} href={rd.routes.ru!}><div className="eyebrow">{duration(rd,'ru')}</div><h3>{rt.title}</h3><p>{rt.description}</p><div className="bottom"><span>{cityPages[r.destination_id]?.name}</span><b>{price(rd.commerce,'ru')}</b></div></Link>;})}</div><Link href={'/ru/all-tours?city='+o.destination_id} prefetch={false}>Все туры {c?.inName} →</Link></div></section>
 <section className="section final" id="booking"><div className="container final-grid"><div><div className="eyebrow" style={{color:'#ff946e'}}>Заявка</div><h2>Запросить этот тур</h2><p>{t.title} · {time}. Укажите дату, количество участников и опыт. Подтвердим технику и условия именно для этого предложения.</p><div className="hero-facts"><a className="btn btn-orange" href={contacts.whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp</a><a className="btn btn-white" href={contacts.telegramContact} target="_blank" rel="noopener noreferrer">Telegram</a><a className="btn btn-ghost" href={contacts.instagram} target="_blank" rel="noopener noreferrer">Instagram</a></div></div><LeadForm offeringId={o.id} locale="ru" type="tour" variants={d.variants.map(v=>({id:v.id,label:v.name.ru??v.id}))} sourcePath={path}/></div></section>
 {legacy.map(id=><span key={id} id={id} aria-hidden="true"/>)}</main><footer className="footer"><Link href="/ru" prefetch={false}>Enduro Vietnam</Link><Link href="/privacy" prefetch={false}>Конфиденциальность</Link><Link href="/site-map" prefetch={false}>Карта сайта</Link><a href={contacts.telegramChannel}>Telegram-канал</a><a href={contacts.youtube}>YouTube</a><a href={contacts.tiktok}>TikTok</a></footer><div className="mobile-bar"><a className="btn btn-ghost" href="#bikes">Байки</a><a className="btn btn-orange" href="#booking">Запросить дату</a></div><EnduroTourRuntime id={o.id}/></div></>;
}
