import {NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {query,batch} from '@/lib/db';
import {AccessError,checkOrigin,digest,limit} from '@/lib/auth';
export const runtime='nodejs';
const input=z.object({name:z.string().trim().min(2).max(100),contact:z.string().trim().min(4).max(200).refine(s=>/@[a-z0-9_]{4,}|^[^\s@]+@[^\s@]+\.[^\s@]+$|[+\d][\d\s()-]{6,}/i.test(s)),city:z.string().max(100).default(''),date:z.string().regex(/^(?:\d{4}-\d{2}-\d{2})?$/).default(''),comment:z.string().max(2000).default(''),consent:z.literal('on'),kind:z.enum(['rental']).optional(),endDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),sourcePath:z.enum(['/ru','/ru/dalat','/ru/nhatrang','/ru/danang','/ru/muine','/ru/destinations/dalat','/ru/destinations/nhatrang','/ru/destinations/danang','/ru/destinations/muine','/ru/destinations/saigon','/ru/destinations/north-vietnam','/ru/rent-motorbike-dalat','/ru/rent-scooter-nhatrang','/ru/rentals/motorbikes','/ru/rentals/cars']).default('/ru')});
export async function POST(req:Request){try{checkOrigin(req);const key=z.string().uuid().parse(req.headers.get('idempotency-key'));const raw=await req.text();if(raw.length>10000)throw new AccessError(413,'Запрос слишком большой');const b=input.parse(JSON.parse(raw));if(b.date&&(Number.isNaN(Date.parse(b.date))||new Date(b.date+'T00:00:00Z').toISOString().slice(0,10)!==b.date||b.date<new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Ho_Chi_Minh'})))throw new AccessError(400,'Выберите корректную будущую дату');
 if(b.kind==='rental'&&(!b.date||!b.endDate||b.endDate<b.date||Number.isNaN(Date.parse(b.endDate))||new Date(b.endDate+'T00:00:00Z').toISOString().slice(0,10)!==b.endDate))throw new AccessError(400,'Проверьте даты начала и окончания аренды');
 const hash=digest(JSON.stringify(b)),[existing]=await query<{id:string;request_hash:string}>('SELECT id,request_hash FROM leads WHERE idempotency_key=$1',[key]);if(existing){if(existing.request_hash!==hash)throw new AccessError(409,'Запрос уже отправлен с другими данными');return NextResponse.json({id:existing.id,saved:true});}
 await limit('home-inquiry:'+b.contact.toLowerCase(),5,3600);const [org]=await query<{id:string}>("SELECT id FROM organizations WHERE slug='enduro-vietnam' AND status='active'");if(!org)throw new AccessError(503,'Приём запросов временно недоступен');const id=randomUUID();const snapshot={title:(b.kind==='rental'?'Подбор аренды · ':'Подбор приключения · ')+(b.city||'Вьетнам'),commerce:{amountMinor:null,currency:b.kind==='rental'?'VND':'USD',basis:'request',unit:null},supplier:'Enduro Vietnam',type:b.kind==='rental'?'rental-inquiry':'consultation',timezone:'Asia/Ho_Chi_Minh'};
 const results=await batch<{id:string;request_hash:string}>([{sql:"INSERT INTO leads(id,idempotency_key,request_hash,offering_id,organization_id,locale,contact,request,snapshot,source_path,utm) VALUES($1,$2,$3,NULL,$4,'ru',$5::jsonb,$6::jsonb,$7::jsonb,$8,'{}'::jsonb) ON CONFLICT(idempotency_key) DO UPDATE SET idempotency_key=leads.idempotency_key RETURNING id,request_hash",params:[id,key,hash,org.id,JSON.stringify({name:b.name,contact:b.contact}),JSON.stringify({date:b.date||null,participants:null,comment:[b.city,b.comment].filter(Boolean).join(' · '),city:b.city,...(b.kind==='rental'?{kind:'rental',endDate:b.endDate}:{} )}),JSON.stringify(snapshot),b.sourcePath]},{sql:"INSERT INTO outbox(id,lead_id,channel) SELECT $1,id,'email' FROM leads WHERE idempotency_key=$2 ON CONFLICT(lead_id,channel) DO NOTHING",params:[randomUUID(),key]},{sql:"INSERT INTO outbox(id,lead_id,channel) SELECT $1,id,'telegram' FROM leads WHERE idempotency_key=$2 ON CONFLICT(lead_id,channel) DO NOTHING",params:[randomUUID(),key]},{sql:"INSERT INTO lead_events(id,lead_id,action) SELECT $1,l.id,'lead_saved' FROM leads l WHERE l.idempotency_key=$2 AND NOT EXISTS(SELECT 1 FROM lead_events e WHERE e.lead_id=l.id AND e.action='lead_saved')",params:[randomUUID(),key]}]);if(results[0].rows[0].request_hash!==hash)throw new AccessError(409,'Запрос уже отправлен с другими данными');return NextResponse.json({id:results[0].rows[0].id,saved:true},{status:201});
}catch(e){return NextResponse.json({error:e instanceof AccessError?e.message:e instanceof z.ZodError?'Проверьте имя, контакт и согласие на обработку данных':'Не удалось сохранить запрос. Повторите позже.'},{status:e instanceof AccessError?e.status:e instanceof z.ZodError?400:503});}}
