import {NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {query,batch} from '@/lib/db';
import {AccessError,checkOrigin,digest,limit} from '@/lib/auth';
import type {Offering} from '@/lib/catalog-types';
export const runtime='nodejs';
const schema=z.object({offeringId:z.string().max(100),locale:z.enum(['ru','en']),name:z.string().trim().min(2).max(100),contact:z.string().trim().min(4).max(200).refine(s=>/@[a-z0-9_]{4,}|^[^\s@]+@[^\s@]+\.[^\s@]+$|[+\d][\d\s()-]{6,}/i.test(s),'Use a phone number, email or Telegram username'),variantId:z.string().max(100).optional(),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),endDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),participants:z.coerce.number().int().min(1).max(100).optional(),comment:z.string().max(2000).default(''),website:z.string().max(200).default(''),consent:z.literal('on'),sourcePath:z.string().regex(/^\/(?!\/)[a-zA-Z0-9/_-]*$/).max(200),utm:z.object({utm_source:z.string().max(150).optional(),utm_medium:z.string().max(150).optional(),utm_campaign:z.string().max(150).optional(),utm_content:z.string().max(150).optional(),utm_term:z.string().max(150).optional()}).default({})});
export async function POST(req:Request){try{
 checkOrigin(req);if(Number(req.headers.get('content-length')??0)>20000)throw new AccessError(413,'Request too large');const key=z.string().uuid().parse(req.headers.get('idempotency-key'));const raw=await req.text();if(raw.length>20000)throw new AccessError(413,'Request too large');const b=schema.parse(JSON.parse(raw));if(b.website)throw new AccessError(400,'Invalid request');const hash=digest(JSON.stringify(b));const [existing]=await query<{id:string;request_hash:string}>('SELECT id,request_hash FROM leads WHERE idempotency_key=$1',[key]);if(existing){if(existing.request_hash!==hash)throw new AccessError(409,'Request key already used');return NextResponse.json({id:existing.id,saved:true});}
 await limit(`lead:${b.contact.toLowerCase()}`,5,3600);
 const [o]=await query<Offering>("SELECT id,organization_id,type,published_data FROM offerings WHERE id=$1 AND id NOT LIKE 'fixture-%' AND published_data IS NOT NULL AND published_data->'translations' ? $2",[b.offeringId,b.locale]);if(!o)throw new AccessError(404,'Offer unavailable');
 const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Ho_Chi_Minh'});if(b.date<today||Number.isNaN(Date.parse(b.date))||new Date(b.date+'T00:00:00Z').toISOString().slice(0,10)!==b.date)throw new AccessError(400,'Choose a valid future date');if(o.type==='rental'&&(!b.endDate||b.endDate<b.date||Number.isNaN(Date.parse(b.endDate))||new Date(b.endDate+'T00:00:00Z').toISOString().slice(0,10)!==b.endDate)||o.type!=='rental'&&!b.participants)throw new AccessError(400,'Check rental dates or participants');const variant=b.variantId?o.published_data!.variants.find(v=>v.id===b.variantId):null;if(b.variantId&&!variant)throw new AccessError(400,'Option unavailable');
 const id=randomUUID(),snapshot={title:o.published_data!.translations[b.locale]!.title,commerce:variant?.commerce??o.published_data!.commerce,variant,tariffs:o.published_data!.tariffs??null,deposit:o.published_data!.deposit??null,conditions:o.published_data!.conditions??{},timezone:'Asia/Ho_Chi_Minh',supplier:o.published_data!.supplier};
 const result=await batch<{id:string;request_hash:string}>([{sql:"INSERT INTO leads(id,idempotency_key,request_hash,offering_id,organization_id,locale,contact,request,snapshot,source_path,utm) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9::jsonb,$10,$11::jsonb) ON CONFLICT(idempotency_key) DO UPDATE SET idempotency_key=leads.idempotency_key RETURNING id,request_hash",params:[id,key,hash,o.id,o.organization_id,b.locale,JSON.stringify({name:b.name,contact:b.contact}),JSON.stringify({date:b.date,endDate:b.endDate??null,participants:b.participants??null,comment:b.comment}),JSON.stringify(snapshot),b.sourcePath,JSON.stringify(b.utm)]},{sql:"INSERT INTO outbox(id,lead_id,channel) SELECT $1,id,'email' FROM leads WHERE idempotency_key=$2 ON CONFLICT(lead_id,channel) DO NOTHING",params:[randomUUID(),key]},{sql:"INSERT INTO outbox(id,lead_id,channel) SELECT $1,id,'telegram' FROM leads WHERE idempotency_key=$2 ON CONFLICT(lead_id,channel) DO NOTHING",params:[randomUUID(),key]},{sql:"INSERT INTO lead_events(id,lead_id,action) SELECT $1,l.id,'lead_saved' FROM leads l WHERE l.idempotency_key=$2 AND NOT EXISTS(SELECT 1 FROM lead_events e WHERE e.lead_id=l.id AND e.action='lead_saved')",params:[randomUUID(),key]}]);if(result[0].rows[0].request_hash!==hash)throw new AccessError(409,'Request key already used');return NextResponse.json({id:result[0].rows[0].id,saved:true}, {status:201});
 }catch(e){return NextResponse.json({error:e instanceof AccessError?e.message:e instanceof z.ZodError?'Проверьте поля / Check the fields':'Заявка не сохранена. Повторите позже / Request not saved. Try again later'}, {status:e instanceof AccessError?e.status:e instanceof z.ZodError?400:503});}}
