import 'server-only';
import {query} from './db';
import type {Locale,Offering,OfferingData,Money} from './catalog-types';
export const prefix=(l:Locale)=>l==='ru'?'/ru':'';
export function price(m:Money,l:Locale){if(m.amountMinor===null)return l==='ru'?'Цена по запросу':'Price on request';const amount=m.currency==='USD'?m.amountMinor/100:m.amountMinor;return `${m.basis==='from'?(l==='ru'?'от ':'from '):''}${new Intl.NumberFormat(l==='ru'?'ru-RU':'en-US',{style:'currency',currency:m.currency,maximumFractionDigits:m.currency==='VND'?0:2}).format(amount)}${m.unit?` / ${{person:l==='ru'?'человек':'person',group:l==='ru'?'группа':'group',day:l==='ru'?'день':'day',week:l==='ru'?'неделя':'week',month:l==='ru'?'месяц':'month','3_days':l==='ru'?'3 дня':'3 days'}[m.unit as 'day']??m.unit}`:''}`;}
export function duration(d:OfferingData,l:Locale){if(!d.duration)return '';return `${d.duration.value} ${d.duration.unit==='hours'?(l==='ru'?'ч.':'hours'):(l==='ru'?'дн.':'days')}`;}
export async function publicOfferings(locale:Locale){return query<Offering>("SELECT id,organization_id,type,category_id,destination_id,slug,published_data,published_at,updated_at,(SELECT slug FROM organizations g WHERE g.id=offerings.organization_id) AS organization_slug FROM offerings WHERE id NOT LIKE 'fixture-%' AND published_data IS NOT NULL AND published_data->'translations' ? $1 ORDER BY published_at DESC,id",[locale]);}
export async function publicOffering(path:string){const [o]=await query<Offering>("SELECT o.id,o.organization_id,o.type,o.category_id,o.destination_id,o.slug,o.published_data,o.published_at,o.updated_at,(SELECT slug FROM organizations g WHERE g.id=o.organization_id) AS organization_slug FROM offerings o JOIN url_registry r ON r.offering_id=o.id WHERE o.id NOT LIKE 'fixture-%' AND r.path=$1 AND r.kind='offering' AND o.published_data IS NOT NULL",[path]);return o??null;}
export async function dictionaries(){const [categories,destinations]=await Promise.all([query<{id:string;slug:string;names:Record<Locale,string>}>("SELECT c.id,c.slug,c.names FROM categories c WHERE c.active AND EXISTS(SELECT 1 FROM offerings o WHERE o.id NOT LIKE 'fixture-%' AND (o.category_id=c.id OR o.published_data->'categoryIds' ? c.id) AND o.published_data IS NOT NULL) ORDER BY c.sort_order,c.id"),query<{id:string;names:Record<Locale,string>;aliases:string[]}>('SELECT id,names,aliases FROM destinations ORDER BY id')]);return {categories,destinations};}
