import {randomBytes,randomUUID,scryptSync} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {TOTP,Secret} from 'otpauth';
import {runSQL} from '../server/sql-client.mjs';
if(process.env.DATABASE_URL)throw new Error('Local-only fixture');const base='http://localhost:3000',id=randomUUID(),email=`${id}@fixture.test`,password=randomBytes(24).toString('hex'),salt=randomBytes(16).toString('hex'),hash=`${salt}:${scryptSync(password,salt,64).toString('hex')}`,checks=[];let cookie;
function check(name,ok){checks.push({name,passed:!!ok});if(!ok)throw new Error(name);}
async function api(body,c){const r=await fetch(base+'/api/admin/auth',{method:'POST',headers:{origin:base,'content-type':'application/json',...(c?{cookie:c}:{})},body:JSON.stringify(body)});return {r,d:await r.json()};}
try{await runSQL([{sql:"INSERT INTO users(id,email,password_hash,role) VALUES($1,$2,$3,'owner')",params:[id,email,hash]}]);const login=await api({action:'login',email,password});cookie=login.r.headers.get('set-cookie').split(';')[0];const start=await api({action:'mfa-start'},cookie);check('Owner can initiate MFA',start.r.status===200);const code=new TOTP({secret:Secret.fromBase32(start.d.secret),issuer:'Enduro Vietnam',label:'Owner',algorithm:'SHA1',digits:6,period:30}).generate();check('Valid TOTP enables MFA',(await api({action:'mfa-confirm',otp:code},cookie)).r.status===200);check('Enabled MFA secret cannot be reissued',(await api({action:'mfa-start'},cookie)).r.status===400);await api({action:'logout'},cookie);check('Password alone fails after MFA enabled',(await api({action:'login',email,password})).r.status===401);check('Incorrect OTP rejected',(await api({action:'login',email,password,otp:'abcdef'})).r.status===401);const valid=await api({action:'login',email,password,otp:code});check('Password and valid OTP succeed',valid.r.status===200);cookie=valid.r.headers.get('set-cookie').split(';')[0];
}finally{await runSQL([{sql:'DELETE FROM audit_log WHERE user_id=$1',params:[id]},{sql:'DELETE FROM recovery_tokens WHERE user_id=$1',params:[id]},{sql:'DELETE FROM users WHERE id=$1',params:[id]}]);await writeFile('.shipstudio/mfa-checks.json',JSON.stringify({checkedAt:new Date().toISOString(),checks,realOwnerMfaChanged:false},null,2)+'\n');}console.log(`${checks.length} MFA checks passed; real owner account unchanged`);
