import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createServer} from 'node:http';
import {randomUUID} from 'node:crypto';
import {launchChrome} from '../.shipstudio/fidelity/headless-chrome.mjs';
import {runSQL} from '../server/sql-client.mjs';
const base=process.env.APP_URL??'http://localhost:3001',report={checkedAt:new Date().toISOString(),widths:process.argv.find(a=>a.startsWith('--widths='))?.slice(9).split(',').map(Number)??[360,520,820,1024,1100,1280,1440],pages:[],checks:[],errors:[]};
const check=(name,passed,detail)=>{report.checks.push({name,passed,detail});if(!passed)report.errors.push({name,detail});};
const assetReport=JSON.parse(await readFile('.shipstudio/ru-home-assets.json','utf8'));let reference=await readFile('content/homepage-ru/reference.html','utf8');
for(const asset of assetReport.files)reference=reference.replaceAll(asset.url,asset.path);
const css=await readFile('content/homepage-ru/styles.css','utf8'),fonts=css.slice(0,css.indexOf('.ru-aggregator'));
reference=reference.replace(/<link[^>]+href="https:\/\/fonts.googleapis.com\/css2[^>]+>/,'<style>'+fonts+'</style>');
const server=createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/'){res.setHeader('Content-Type','text/html');res.end(reference);return;}if(!pathname.startsWith('/assets/homepage-ru/')||pathname.includes('..')){res.writeHead(404);res.end();return;}const data=await readFile('public'+pathname);res.setHeader('Content-Type',pathname.endsWith('.webp')?'image/webp':'font/ttf');res.end(data);}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const referenceBase='http://127.0.0.1:'+server.address().port;
const chrome=await launchChrome({tool:'ru-home-qa',basePort:9380});await mkdir('.shipstudio/qa/ru-home',{recursive:true});
async function tab(){const target=await(await fetch(`http://127.0.0.1:${chrome.port}/json/new?about:blank`,{method:'PUT'})).json(),ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map(),errors=[];ws.addEventListener('message',e=>{const m=JSON.parse(String(e.data));if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);if(pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id);}});return {errors,id:target.id,send:(method,params={})=>new Promise((resolve,reject)=>{const n=++id,t=setTimeout(()=>reject(new Error('CDP timeout '+method)),25000);pending.set(n,m=>{clearTimeout(t);resolve(m);});ws.send(JSON.stringify({id:n,method,params}));}),close:()=>ws.close()};}
async function evaluate(p,expression){const r=await p.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.result?.exceptionDetails)throw new Error(r.result.exceptionDetails.text);return r.result?.result?.value;}
const selectors=['.container.header-in','.hero-content','.hero h1','.hero-claim','.hero-copy','.finder','.activity-grid','.format-card','.rental-info-grid','.immersive-content','.section-head h2','.guide-grid','.faq-grid'];
async function load(p,url,width){await p.send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});await p.send('Runtime.enable');await p.send('Page.enable');await p.send('Page.navigate',{url});for(let i=0;i<150;i++){if(await evaluate(p,"document.readyState==='complete'&&!!document.querySelector('.hero h1')"))break;await new Promise(r=>setTimeout(r,100));}await evaluate(p,"(async()=>{await Promise.race([Promise.all([document.fonts.ready,...[...document.images].map(i=>i.decode().catch(()=>{}))]),new Promise(r=>setTimeout(r,5000))]);})()");}
const expr=`(()=>{const result={};for(const s of ${JSON.stringify(selectors)}){const el=document.querySelector(s),c=getComputedStyle(el),r=el.getBoundingClientRect();result[s]={width:r.width,fontSize:c.fontSize,fontWeight:c.fontWeight,lineHeight:c.lineHeight,fontFamily:c.fontFamily,padding:c.padding,gap:c.gap,columns:c.gridTemplateColumns,color:c.color};}return result;})()`;
try{const r=await tab(),p=await tab();try{for(const width of report.widths){console.log('Checking width '+width);await load(r,referenceBase,width);await load(p,base+'/ru',width);const original=await evaluate(r,expr),rebuilt=await evaluate(p,expr);const diffs=[];for(const selector of selectors)for(const key of Object.keys(original[selector]))if(key==='width'?Math.abs(original[selector][key]-rebuilt[selector][key])>1:original[selector][key]!==rebuilt[selector][key])diffs.push({selector,key,original:original[selector][key],rebuilt:rebuilt[selector][key]});const unexpected=diffs.filter(d=>!(d.selector==='.rental-info-grid'&&width>=1000));check('Unchanged design roles '+width,unexpected.length===0,unexpected);
await evaluate(p,"scrollTo(0,120);window.dispatchEvent(new Event('scroll'))");check('Logo background removed '+width,await evaluate(p,"(()=>{const c=getComputedStyle(document.querySelector('.header .logo'));return c.backgroundColor==='rgba(0, 0, 0, 0)'&&c.boxShadow==='none'&&c.backdropFilter==='none';})()"));
const health=await evaluate(p,"({overflow:document.documentElement.scrollWidth>innerWidth+1,broken:[...document.images].filter(i=>!i.naturalWidth).map(i=>i.src),h1s:document.querySelectorAll('h1').length,sections:[...document.querySelectorAll('main>section')].map(e=>e.id)})");check('Layout/images '+width,!health.overflow&&!health.broken.length&&health.h1s===1,health);const chips=await evaluate(p,"[...document.querySelectorAll('.city-chip')].map(e=>e.getBoundingClientRect().height)");check('Uniform city heights '+width,Math.max(...chips)-Math.min(...chips)<1,chips);
await evaluate(p,"scrollTo(0,0);document.getElementById('cityInput').click()");const panel=await evaluate(p,"(()=>{const panel=document.getElementById('cityAutocomplete');panel.scrollIntoView({block:'end',behavior:'instant'});const r=panel.getBoundingClientRect(),hit=document.elementFromPoint(r.left+20,Math.min(r.bottom-15,innerHeight-20));return {visible:!!hit&&panel.contains(hit),overflow:getComputedStyle(document.querySelector('.hero')).overflowY,bounds:{top:r.top,bottom:r.bottom,height:r.height},open:panel.closest('.field').className,hit:hit?.outerHTML.slice(0,200),buttons:panel.children.length};})()");check('City dropdown stays above following section '+width,panel.visible,panel);await evaluate(p,"document.getElementById('cityInput').blur();document.querySelector('.hero h1').click();document.getElementById('activityInput').click()");const activityPanel=await evaluate(p,"(()=>{const panel=document.getElementById('activityAutocomplete');panel.scrollIntoView({block:'end',behavior:'instant'});const r=panel.getBoundingClientRect(),hit=document.elementFromPoint(r.left+20,Math.min(r.bottom-15,innerHeight-20));return !!hit&&panel.contains(hit);})()");check('Activity dropdown visible '+width,activityPanel);await evaluate(p,"document.getElementById('activityInput').blur();document.querySelector('.hero h1').click()");
if(width>=1000){await p.send('Emulation.setDeviceMetricsOverride',{width,height:720,deviceScaleFactor:1,mobile:false});const rental=await evaluate(p,"({height:document.getElementById('rentals').getBoundingClientRect().height,available:innerHeight-76,clipped:[...document.querySelectorAll('.rental-info-panel,.rental-hero-card')].some(e=>e.scrollHeight>e.clientHeight+1),boxes:[...document.querySelectorAll('.rental-info-panel,.rental-hero-card')].map(e=>({class:e.className,scroll:e.scrollHeight,client:e.clientHeight}))})");check('Rental fits desktop screen '+width,rental.height<=rental.available&&!rental.clipped,rental);await p.send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});}
report.pages.push({width,original,rebuilt,health});const shot=await p.send('Page.captureScreenshot',{format:'png'});await writeFile('.shipstudio/qa/ru-home/'+width+'.png',Buffer.from(shot.result.data,'base64'));
await evaluate(p,"document.getElementById('menuButton').click()");check('Menu opens '+width,await evaluate(p,"document.getElementById('menuDrawer').classList.contains('open')&&!document.getElementById('menuDrawer').inert"));await p.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',windowsVirtualKeyCode:27});check('Escape closes menu '+width,await evaluate(p,"!document.getElementById('menuDrawer').classList.contains('open')&&document.body.style.overflow!=='hidden'"));await evaluate(p,"document.querySelector('.float-main').click()");check('Modal opens '+width,await evaluate(p,"document.getElementById('bookingModal').classList.contains('open')"));await evaluate(p,"document.getElementById('modalClose').click()");check('Modal closes '+width,await evaluate(p,"!document.getElementById('bookingModal').classList.contains('open')"));}
check('No runtime exceptions',p.errors.length===0,p.errors);
await evaluate(p,"document.getElementById('cityInput').value='Фукуок';document.getElementById('heroSearch').click()");check('Future city opens consultation',await evaluate(p,"document.getElementById('bookingModal').classList.contains('open')&&document.querySelector('#modalForm textarea').value.includes('Фукуок')"));
await evaluate(p,"document.getElementById('modalClose').click();document.getElementById('cityInput').value='Нячанг';document.getElementById('activityInput').value='Аренда скутеров';document.getElementById('heroSearch').click()");await new Promise(r=>setTimeout(r,500));check('Rental search separate from tours',await evaluate(p,"location.pathname==='/ru/rentals/motorbikes'&&new URLSearchParams(location.search).get('city')==='nhatrang'"));
}finally{r.close();p.close();await fetch(`http://127.0.0.1:${chrome.port}/json/close/${r.id}`);await fetch(`http://127.0.0.1:${chrome.port}/json/close/${p.id}`);}
const priceHtml=await(await fetch(base+'/ru')).text();check('Price overview covers multiple cities and activities',priceHtml.includes('Нячанг')&&priceHtml.includes('Дананг')&&priceHtml.includes('Хошимин → Нячанг')&&priceHtml.includes('planned-format')&&priceHtml.includes('Дайвинг и море'));check('Enduro navigation uses relevant catalog',priceHtml.includes('href=\"/ru/all-tours?q=эндуро\">Эндуро'));
const contacts=JSON.parse(await readFile('content/homepage-ru/contacts.json','utf8')),html=await(await fetch(base+'/ru')).text();for(const [name,url]of Object.entries(contacts))check('Contact URL '+name,html.includes('href=\"'+url.replaceAll('&','&amp;')+'\"')||html.includes('href=\"'+url+'\"'));check('Confirmed contacts not intercepted as placeholders',[...html.matchAll(/<a\b[^>]*>/g)].filter(m=>/href=\"https?:/.test(m[0])).every(m=>!m[0].includes('social-url-needed')));
const key=randomUUID(),contact='ru-home-check-'+key+'@example.invalid',payload={name:'Проверка главной',contact,city:'Фукуок',date:'',comment:'Проверочная заявка; будет удалена',consent:'on'};let leadId;
try{const submit=body=>fetch(base+'/api/home-inquiries',{method:'POST',headers:{origin:base,'content-type':'application/json','idempotency-key':key},body:JSON.stringify(body)});const first=await submit(payload),saved=await first.json();leadId=saved.id;check('General inquiry committed',first.status===201&&saved.saved,{status:first.status});const repeat=await submit(payload),again=await repeat.json();check('Inquiry retry does not duplicate',repeat.status===200&&again.id===leadId);const conflict=await submit({...payload,comment:'Changed'});check('Idempotency conflict rejected',conflict.status===409);const invalid=await submit({...payload,consent:''});check('Consent required',invalid.status===400);const csrf=await fetch(base+'/api/home-inquiries',{method:'POST',headers:{origin:'https://invalid.example','content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify(payload)});check('Foreign origin blocked',csrf.status===403);if(leadId){const [leads,jobs]=await runSQL([{sql:'SELECT offering_id,source_path FROM leads WHERE id=$1',params:[leadId]},{sql:'SELECT channel FROM outbox WHERE lead_id=$1',params:[leadId]}]);check('General request has no fabricated offering',leads.rows[0].offering_id===null&&leads.rows[0].source_path==='/ru');check('Both notifications queued once',jobs.rows.length===2);}}
finally{if(leadId)await runSQL([{sql:'DELETE FROM outbox WHERE lead_id=$1',params:[leadId]},{sql:'DELETE FROM lead_events WHERE lead_id=$1',params:[leadId]},{sql:'DELETE FROM leads WHERE id=$1',params:[leadId]}]);await runSQL([{sql:'DELETE FROM rate_limits WHERE key=$1',params:['home-inquiry:'+contact]}]);}
}finally{chrome.close();server.close();await writeFile('.shipstudio/ru-home-checks.json',JSON.stringify(report,null,2)+'\n');}
console.log(JSON.stringify({widths:report.widths,checks:report.checks.length,errors:report.errors}));if(report.errors.length)process.exitCode=1;
