/* Public read-only showcase. The application remains the owner of live forms/DB. */
(()=>{
const prefix='/enduro-vietnam-showcase',localPath=location.pathname.slice(prefix.length).replace(/\/$/,'')||'/',ru=localPath.startsWith('/ru');
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a)return;let href=a.getAttribute('href');if(href.startsWith('/')&&!href.startsWith('//')&&!href.startsWith(prefix+'/')){a.setAttribute('href',prefix+href);href=prefix+href;}if(href.startsWith(prefix+'/admin')||href.startsWith(prefix+'/api')){e.preventDefault();location.href='https://t.me/mototourvietnam';}},true);
const form=document.querySelector('.catalog-filters');if(!form)return;
fetch(prefix+'/catalog.json').then(r=>r.json()).then(data=>{
const inventory=data.catalogs[localPath]||[],params=new URLSearchParams(location.search);form.querySelectorAll('[name]').forEach(e=>{if(params.has(e.name)&&!e.disabled)e.value=params.get(e.name);});
const selected=k=>params.get(k)||'',fixedCity=form.querySelector('[name=city]')?.disabled?form.querySelector('[name=city]').value:'',fixedCategory=form.querySelector('[name=category]')?.disabled?form.querySelector('[name=category]').value:'';
let entries=inventory.map(c=>({card:c,o:data.offers.find(o=>o.id===c.id)})).filter(x=>x.o);
entries=entries.filter(({o})=>{const t=o.translations[ru?'ru':'en'],text=JSON.stringify(t).toLowerCase()+' '+o.city;const city=fixedCity||selected('city'),category=fixedCategory||selected('category'),unit=selected('unit'),tariff=unit&&o.type==='rental'?o.tariffs?.find(t=>t.period===unit):null,c=tariff?{...tariff,unit:tariff.period}:o.commerce,v=o.vehicle||{},duration=o.duration,currency=selected('currency'),comparable=currency&&unit,scale=currency==='USD'?100:1;
return (!selected('q')||text.includes(selected('q').toLowerCase()))&&(!city||o.city===city||o.endCity===city)&&(!category||o.category===category||o.categories.includes(category))&&(!selected('type')||o.type===selected('type'))&&(!currency||c.currency===currency)&&(!unit||c.unit===unit)&&(!comparable||!selected('priceMin')||c.amountMinor!==null&&c.amountMinor>=Number(selected('priceMin'))*scale)&&(!comparable||!selected('priceMax')||c.amountMinor!==null&&c.amountMinor<=Number(selected('priceMax'))*scale)&&(!selected('durationMin')||duration&&duration.unit===(selected('durationUnit')||'hours')&&duration.value>=Number(selected('durationMin')))&&(!selected('durationMax')||duration&&duration.unit===(selected('durationUnit')||'hours')&&duration.value<=Number(selected('durationMax')))&&(!selected('level')||o.level?.toLowerCase().includes(selected('level').toLowerCase()))&&(!selected('engineMin')||typeof v.engineCC==='number'&&v.engineCC>=Number(selected('engineMin')))&&(!selected('seats')||typeof v.seats==='number'&&v.seats>=Number(selected('seats')))&&(!selected('gearbox')||String(v.gearbox||'').toLowerCase()===selected('gearbox'))&&(!selected('drive')||typeof v.selfDrive==='boolean'&&v.selfDrive===(selected('drive')==='self'));});
if(selected('sort')==='price'&&selected('currency')&&selected('unit'))entries.sort((a,b)=>{const amount=o=>(o.type==='rental'?o.tariffs?.find(t=>t.period===selected('unit')):o.commerce)?.amountMinor??Infinity;return amount(a.o)-amount(b.o)||a.o.id.localeCompare(b.o.id);});
const count=document.querySelector('[data-results]')||form.parentElement.querySelector('p[aria-live]'),pages=Math.ceil(entries.length/9),page=Math.max(1,Number(selected('page'))||1);if(count){count.textContent=ru?'Найдено '+entries.length+' позиций':entries.length+' offers';count.dataset.results=entries.length;}
let grid=document.querySelector('#rentalGrid,.offering-grid');if(!grid){grid=document.createElement('div');grid.className=localPath.includes('rent')?'rental-grid':'offering-grid';count?.after(grid);}grid.innerHTML=entries.slice((page-1)*9,page*9).map(c=>c.card.html).join('');document.querySelector('.catalog-empty')?.remove();if(!entries.length)grid.textContent=ru?'Предложения не найдены. Измените фильтры.':'No matching offers. Try different filters.';
let pagination=document.querySelector('.pagination');if(!pagination){pagination=document.createElement('nav');pagination.className='pagination';pagination.setAttribute('aria-label',ru?'Страницы каталога':'Catalog pages');grid.after(pagination);}pagination.replaceChildren();for(let n=1;n<=pages;n++){const a=document.createElement('a'),q=new URLSearchParams(params);q.set('page',n);a.href=prefix+localPath+'/?'+q+(localPath.includes('rent')?'#models':'');a.textContent=n;if(n===page)a.setAttribute('aria-current','page');pagination.append(a);}
window.showcaseCatalogReady=true;
}).catch(()=>{window.showcaseCatalogReady=false;});
})();
