'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
export function RentalInquiryForm({offers,city,path}:{offers:{id:string;label:string}[];city:string;path:string}){
 const [ready,setReady]=useState(false),[selected,setSelected]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[start,setStart]=useState('');const key=useRef<string|null>(null),pending=useRef(false);const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Ho_Chi_Minh'});
 useEffect(()=>{setReady(true);const select=(e:Event)=>{const id=(e as CustomEvent<string>).detail;if(offers.some(o=>o.id===id)&&!pending.current){setSelected(id);key.current=null;setSaved(false);setStatus('');document.getElementById('rental-model')?.focus({preventScroll:true});}};window.addEventListener('rental-select',select);return()=>window.removeEventListener('rental-select',select);},[offers]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(pending.current||saved)return;const form=e.currentTarget;if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));pending.current=true;setBusy(true);setStatus('Сохраняем запрос…');key.current??=crypto.randomUUID();try{const response=await fetch(selected?'/api/leads':'/api/home-inquiries',{method:'POST',headers:{'content-type':'application/json','idempotency-key':key.current},body:JSON.stringify(selected?{...values,offeringId:selected,locale:'ru',sourcePath:path}:{name:values.name,contact:values.contact,date:values.date,endDate:values.endDate,comment:values.comment,consent:values.consent,city,kind:'rental',sourcePath:path})});const result=await response.json();if(!response.ok||!result.saved)throw new Error(result.error||'Не удалось сохранить запрос');setSaved(true);setStatus('Запрос аренды сохранён. Наличие техники, тариф и место выдачи подтверждаем после проверки.');}catch(error){setStatus(error instanceof Error?error.message:'Не удалось сохранить запрос. Повторите позже.');}finally{pending.current=false;setBusy(false);}}
 return <form className="form rental-inquiry" data-ready={ready} onSubmit={submit} method="post" aria-label="Запрос аренды"><label className="full" htmlFor="rental-model">Модель<select id="rental-model" name="offeringId" value={selected} disabled={busy} onChange={e=>{setSelected(e.target.value);key.current=null;setSaved(false);setStatus('');}}><option value="">Помогите выбрать технику</option>{offers.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label><label>Имя *<input name="name" autoComplete="name" required minLength={2} maxLength={100}/></label><label>Контакт *<input name="contact" autoComplete="tel" required minLength={4} maxLength={200} placeholder="WhatsApp, @Telegram или email"/></label><label>Начало аренды *<input name="date" type="date" min={today} value={start} onChange={e=>setStart(e.target.value)} required/></label><label>Окончание аренды *<input name="endDate" type="date" min={start||today} required/></label><label className="full">Пожелания<textarea name="comment" maxLength={2000} placeholder="Срок, опыт, место выдачи и пожелания к технике"/></label><label className="consent full"><input type="checkbox" name="consent" value="on" required/><span>Согласен на обработку данных для ответа на запрос. <Link href="/privacy" prefetch={false}>Политика конфиденциальности</Link></span></label><button className="btn btn-primary full" type="submit" disabled={!ready||busy||saved}>{saved?'Запрос сохранён':busy?'Сохраняем…':'Запросить аренду →'}</button><p role="status" aria-live="polite">{status}</p><p className="rental-offline">Для отправки формы включите JavaScript или напишите в мессенджер рядом.</p></form>;
}
