import Link from 'next/link';
import type {Offering} from '@/lib/catalog-types';
import {price,publicOfferings} from '@/lib/catalog';
import {cityPages} from '@/lib/city-pages';
import {rentalDeposit,rentalPeriodLabels,rentalTariffLabel} from '@/lib/rentals';
import {LeadForm} from '@/components/catalog/LeadForm';
import contacts from '@/content/homepage-ru/contacts.json';
import {RentalChrome} from './RentalChrome';
import {RentalPhoto} from './RentalPhoto';
import {RentalCard} from './RentalCard';
export async function RentalDetail({offering:o,path}:{offering:Offering;path:string}){const d=o.published_data!,t=d.translations.ru!,c=cityPages[o.destination_id],related=(await publicOfferings('ru')).filter(x=>x.type==='rental'&&x.destination_id===o.destination_id&&x.id!==o.id).slice(0,3);return <RentalChrome path={path} alternate={d.routes.en}><main data-rental-detail={o.id}>
 <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><Link href={'/ru/rentals/motorbikes?city='+o.destination_id} prefetch={false}>Аренда · {c?.name}</Link></div><h1>{t.title}</h1>{d.vehicle?.inventoryCode&&<span className="inventory">Позиция № {String(d.vehicle.inventoryCode)}</span>}<p>{t.description}</p><div className="hero-price"><strong>{price(d.commerce,'ru')}</strong></div><div className="hero-actions"><a className="btn btn-primary" href="#request">Запросить аренду</a><a className="btn btn-secondary" href="#rates">Все тарифы</a></div></div><div className="hero-media">{d.photos[0]&&<RentalPhoto src={d.photos[0].src} alt={d.photos[0].alt.ru||t.title} eager/>}<div className="hero-badge"><b>Залог отдельно: {rentalDeposit(o)}</b><span>Даты и условия подтверждаются после заявки.</span></div></div></div></section>
 <section className="quick"><nav className="container quick-row" aria-label="Разделы аренды">{[['rates','Тарифы'],['conditions','Условия'],['photos','Фотографии'],['models','Другие модели'],['contacts','Запросить аренду']].map(([id,label])=><a key={id} className="quick-chip" href={'#'+id}>{label}</a>)}</nav></section>
 <section className="section" id="rates"><div className="container"><div className="section-head"><div><div className="eyebrow">Стоимость</div><h2>Тарифы аренды</h2></div><p>Тариф относится к этой позиции каталога. Залог учитывается отдельно.</p></div><table className="rental-rates"><caption>{t.title}</caption><thead><tr><th scope="col">Период</th><th scope="col">Стоимость аренды</th></tr></thead><tbody>{(d.tariffs??[]).map(rate=><tr key={rate.id} data-rate={rate.period}><th scope="row">{rentalPeriodLabels[rate.period]??rate.period}</th><td>{rentalTariffLabel(rate)}</td></tr>)}</tbody></table><div className="deposit"><span>Залог отдельно</span><strong>{rentalDeposit(o)}</strong></div></div></section>
 <section className="section soft" id="conditions"><div className="container"><div className="section-head"><div><div className="eyebrow">Перед поездкой</div><h2>Характеристики и условия</h2></div><p>Точка выдачи, документы, комплектация и условия возврата уточняются до подтверждения.</p></div><div className="rules-grid"><div className="rules-main"><h3>{t.title}</h3><div className="rule-list">{Object.entries(d.vehicle??{}).filter(([key,value])=>value!==null&&!['inventoryCode','model','kind'].includes(key)).map(([key,value])=><div className="rule" key={key}><b>{({engineCC:'Двигатель, см³',gearbox:'Коробка передач',seats:'Мест',luggage:'Багаж',fuel:'Топливо',mileage:'Пробег',documents:'Документы',pickup:'Выдача',return:'Возврат',damage:'Повреждения',cancellation:'Отмена',selfDrive:'Без водителя'} as Record<string,string>)[key]??key}</b><span>{typeof value==='boolean'?(value?'Да':'Нет'):({automatic:'Автомат',manual:'Механика'} as Record<string,string>)[String(value)]??String(value)}</span></div>)}</div>{t.body.map((p,i)=><p key={i}>{p}</p>)}{typeof d.conditions?.ru==='string'&&<p style={{whiteSpace:'pre-line'}}>{d.conditions.ru}</p>}{typeof d.handoff?.ru==='string'&&<p style={{whiteSpace:'pre-line'}}>{d.handoff.ru}</p>}<p>Комплектацию, наличие на выбранные даты и правила использования подтверждаем с организатором.</p></div><div className="rules-side"><div className="note"><h3>Выдача и возврат</h3><p>Согласуйте время, место получения, документы и состояние топлива. Осмотрите технику перед выдачей.</p></div><div className="note orange"><h3>Организатор</h3><p>{o.organization_slug?<Link href={'/ru/partners/'+o.organization_slug} prefetch={false}>{d.supplier}</Link>:d.supplier}</p><p>Ответственность, залог и условия отмены согласуются до бронирования.</p></div></div></div></div></section>
 <section className="section" id="photos"><div className="container"><div className="section-head"><div><div className="eyebrow">Техника</div><h2>Фотографии</h2></div><p>Все фотографии этой позиции из опубликованного каталога.</p></div><div className="detail-gallery">{d.photos.map(im=><a href={im.src} key={im.src} target="_blank" rel="noopener noreferrer" aria-label={'Открыть фото · '+t.title}><RentalPhoto src={im.src} alt={im.alt.ru||t.title}/></a>)}</div></div></section>
 <section className="section soft" id="models"><div className="container"><div className="section-head"><div><div className="eyebrow">Другие варианты</div><h2>Сравните технику</h2></div><Link prefetch={false} href={'/ru/rentals/motorbikes?city='+o.destination_id}>Весь каталог в {c?.inName} →</Link></div><div className="rental-grid">{related.map(r=><RentalCard key={r.id} offering={r}/>)}</div></div></section>
 <section className="final" id="contacts"><div className="container final-grid"><div><div className="eyebrow">Заявка · {c?.name}</div><h2>Запросить {t.title}</h2><p>Укажите даты аренды и удобный способ связи. Подтвердим наличие именно этой позиции, тариф, залог и место выдачи.</p><div className="contact-row"><a href={contacts.whatsapp}>WhatsApp</a><a href={contacts.telegramContact}>Telegram</a><a href={contacts.instagram}>Instagram</a>{o.destination_id==='dalat'&&<a href={contacts.googleMaps}>Google Maps · Далат</a>}</div></div><LeadForm offeringId={o.id} locale="ru" type="rental" variants={d.variants.map(v=>({id:v.id,label:v.name.ru??v.id}))} sourcePath={path}/></div></section>
 </main></RentalChrome>;}
