import Link from 'next/link';
import {readFileSync} from 'node:fs';
import contacts from '@/content/homepage-ru/contacts.json';
import {cityPages,cityHref} from '@/lib/city-pages';
import {getExportedPage} from '@/lib/exported-content';
import {RentalRuntime} from './RentalRuntime';
export function RentalChrome({path,alternate,children}:{path:string;alternate?:string;children:React.ReactNode}){const ids=new Set(['drawer','menuOpen','menuClose','drawerBackdrop','models','conditions','process','team','routes','faq','contacts','request','rates','photos']);const anchors=getExportedPage(path)?.anchors.filter(id=>!ids.has(id))??[];return <><style dangerouslySetInnerHTML={{__html:readFileSync('content/rentals/styles.css','utf8')}}/><div className="rental-page" data-path={path}>
 <header className="site-header"><div className="container header-inner"><Link className="brand" prefetch={false} href="/ru"><img src="/assets/homepage-ru/e0b769d07f70df9595cb.webp" width={158} height={85} alt="Эндуро Вьетнам"/></Link><nav className="nav-shell" aria-label="Основная навигация"><Link prefetch={false} href="/ru/destinations">Города</Link><Link prefetch={false} href="/ru/all-tours?q=эндуро">Эндуро</Link><Link className="active" prefetch={false} href="/ru/rentals/motorbikes">Аренда</Link><a href="#contacts">Контакты</a></nav><div className="header-actions">{alternate&&<Link prefetch={false} className="icon-btn" href={alternate} lang="en">EN</Link>}<a className="icon-btn" href={contacts.telegramContact} target="_blank" rel="noopener noreferrer" aria-label="Telegram">TG</a><a className="icon-btn" href={contacts.whatsapp} target="_blank" rel="noopener noreferrer" aria-label="WhatsApp">WA</a><button className="menu-btn" id="menuOpen" type="button" aria-controls="drawer" aria-expanded="false">Меню</button></div></div></header>
 <div className="drawer-backdrop" id="drawerBackdrop"/><aside className="drawer" id="drawer" role="dialog" aria-modal="true" aria-label="Навигация по сайту" aria-hidden="true" inert><button className="drawer-close" id="menuClose" type="button" aria-label="Закрыть меню">×</button><div className="container drawer-grid"><div><h3>Города и направления</h3>{Object.entries(cityPages).map(([id,c])=><Link key={id} href={cityHref(id)} prefetch={false}>{c.name}</Link>)}</div><div><h3>Туры и аренда</h3><Link href="/ru/all-tours?q=эндуро" prefetch={false}>Эндуро</Link><Link href="/ru/all-tours" prefetch={false}>Все туры</Link><Link href="/ru/rent-motorbike-dalat" prefetch={false}>Аренда в Далате</Link><Link href="/ru/rent-scooter-nhatrang" prefetch={false}>Аренда в Нячанге</Link><Link href="/ru/rentals/motorbikes" prefetch={false}>Вся мототехника</Link>{alternate&&<Link href={alternate} lang="en" prefetch={false}>English</Link>}</div><div><h3>Связь</h3><a href={contacts.whatsapp}>WhatsApp</a><a href={contacts.telegramContact}>Telegram</a><a href={contacts.instagram}>Instagram</a><a href={contacts.telegramChannel}>Telegram-канал</a><a href="#contacts">Запросить аренду</a></div></div></aside>
 {children}{anchors.map(id=><span id={id} key={id} aria-hidden="true"/>)}<footer className="footer"><div className="container"><div className="footer-grid"><div><div className="footer-brand">ЭНДУРО ВЬЕТНАМ</div><p>Туры, активный отдых и аренда транспорта во Вьетнаме.</p></div><div><h4>Аренда</h4><Link href="/ru/rent-motorbike-dalat" prefetch={false}>Далат</Link><Link href="/ru/rent-scooter-nhatrang" prefetch={false}>Нячанг</Link><Link href="/ru/rentals/motorbikes" prefetch={false}>Вся аренда мототехники</Link></div><div><h4>Путешествия</h4><Link href="/ru/destinations" prefetch={false}>Города</Link><Link href="/ru/all-tours" prefetch={false}>Все туры</Link><Link href="/privacy" prefetch={false}>Конфиденциальность</Link><Link href="/site-map" prefetch={false}>Карта сайта</Link></div><div><h4>Связь</h4><a href={contacts.whatsapp}>WhatsApp</a><a href={contacts.telegramContact}>Telegram</a><a href={contacts.instagram}>Instagram</a><a href={contacts.youtube}>YouTube</a><a href={contacts.tiktok}>TikTok</a></div></div><div className="copyright">© {new Date().getFullYear()} Enduro Vietnam</div></div></footer><RentalRuntime path={path}/></div></>;}
