'use client';
import {useEffect} from 'react';
export function RentalRuntime({path}:{path:string}){useEffect(()=>{
 const root=document.querySelector<HTMLElement>('.rental-page');if(!root)return;
 const controller=new AbortController(),signal=controller.signal,drawer=root.querySelector<HTMLElement>('#drawer')!,backdrop=root.querySelector<HTMLElement>('#drawerBackdrop')!,trigger=root.querySelector<HTMLElement>('#menuOpen')!,header=root.querySelector<HTMLElement>('.site-header')!,previous=document.body.style.overflow;let timer:ReturnType<typeof setTimeout>;
 function menu(open:boolean,restore=true){clearTimeout(timer);drawer.classList.toggle('open',open);backdrop.classList.toggle('open',open);drawer.inert=!open;drawer.setAttribute('aria-hidden',String(!open));trigger.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':previous;if(open){const ms=Math.max(...getComputedStyle(drawer).transitionDuration.split(',').map(t=>parseFloat(t)*1000));timer=setTimeout(()=>drawer.querySelector<HTMLElement>('#menuClose')?.focus({preventScroll:true}),ms+50);}else if(restore)trigger.focus({preventScroll:true});}
 trigger.addEventListener('click',()=>menu(true),{signal});root.querySelector('#menuClose')!.addEventListener('click',()=>menu(false),{signal});backdrop.addEventListener('click',()=>menu(false),{signal});drawer.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu(false,false),{signal}));
 document.addEventListener('keydown',event=>{if(!drawer.classList.contains('open'))return;if(event.key==='Escape'){event.preventDefault();menu(false);}if(event.key==='Tab'){const nodes=[...drawer.querySelectorAll<HTMLElement>('button,a[href]')],first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}},{signal});
 const scroll=()=>header.classList.toggle('scrolled',scrollY>50);window.addEventListener('scroll',scroll,{passive:true,signal});scroll();
 root.addEventListener('click',e=>{const a=(e.target as Element).closest<HTMLElement>('[data-select-rental]');if(!a||!root.querySelector('.rental-inquiry'))return;e.preventDefault();window.dispatchEvent(new CustomEvent('rental-select',{detail:a.dataset.selectRental}));root.querySelector('#contacts')?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});},{signal});
 root.dataset.rentalReady='true';return()=>{clearTimeout(timer);controller.abort();document.body.style.overflow=previous;delete root.dataset.rentalReady;};
 },[path]);return null;}
