import Link from 'next/link';
import type {Offering} from '@/lib/catalog-types';
import {cityPages,cityHref} from '@/lib/city-pages';
import {price} from '@/lib/catalog';
import {rentalDailyMinimum} from '@/lib/rentals';
import contacts from '@/content/homepage-ru/contacts.json';
import {RentalChrome} from './RentalChrome';
import {RentalCard} from './RentalCard';
import {RentalPhoto} from './RentalPhoto';
import {RentalInquiryForm} from './RentalInquiryForm';
type Search=Record<string,string|string[]|undefined>;
export function RentalListing({path,alternate,selectedCity,all,filtered,visible,filters,search,pages,page,pageLinks,sortNotice,isCars=false}:{path:string;alternate:string;selectedCity:string;all:Offering[];filtered:Offering[];visible:Offering[];filters:React.ReactNode;search:Search;pages:number;page:number;pageLinks:string[];sortNotice:boolean;isCars?:boolean}){
 const c=cityPages[selectedCity],scope=all.filter(o=>!selectedCity||o.destination_id===selectedCity),minimum=rentalDailyMinimum(scope),hero=scope.find(o=>/nvx/i.test(o.published_data!.translations.ru!.title))??scope[0],city=c?.name??'Вьетнам',title=isCars?'Аренда автомобилей во Вьетнаме':c?`Аренда скутеров и мотоциклов в ${c.inName}`:'Аренда скутеров и мотоциклов во Вьетнаме';
 const quick=[['models','Модели'],['conditions','Условия'],['process','Как арендовать'],['team','Контакты'],['routes','Куда поехать'],['faq','FAQ']];
 const chip=(params:Record<string,string>)=>{const q=new URLSearchParams();for(const [k,v]of Object.entries(search))if(typeof v==='string'&&!['page','priceMin','priceMax','currency','unit','sort'].includes(k))q.set(k,v);for(const [k,v]of Object.entries(params))q.set(k,v);return path+(q.size?'?'+q:'')+'#models';};
 const faq=[['Что входит в стоимость?','Комплектация зависит от конкретной модели. Шлемы, замок, кофр и дополнительные услуги подтверждаются до выдачи техники.'],['Какой залог?','Залог указан отдельно от аренды в карточке каждой позиции. Если сумма ещё не опубликована, уточним её вместе с условиями возврата.'],['Есть ли доставка?','Возможность доставки, адрес, время и стоимость согласуются с организатором. Бесплатную доставку без подтверждения не обещаем.'],['Какие документы нужны?','Требования к документам и допуску к управлению уточняются для выбранной техники до подтверждения аренды.'],['Можно арендовать на неделю или месяц?','Опубликованные тарифы на разные периоды показаны в карточках. Для отсутствующего тарифа можно отправить запрос; наличие проверяем на конкретные даты.']];
 const ideas=c?[{title:'Знакомство с городом',copy:'Узнайте о направлении и доступных форматах отдыха.',href:cityHref(selectedCity),photo:c.photos[0]},{title:'Активности и поездки',copy:'Посмотрите опубликованные предложения в этом городе.',href:'/ru/all-tours?city='+selectedCity,photo:c.photos[1]??c.photos[0]},{title:'Нужен маршрут?',copy:'Обсудим пожелания и формат поездки.',href:'#contacts',photo:c.photos[2]??c.photos[0]}]:Object.entries(cityPages).filter(([id])=>['dalat','nhatrang','danang'].includes(id)).map(([id,x])=>({title:x.name,copy:'Туры и активный отдых в этом направлении.',href:cityHref(id),photo:x.photos[0]}));
 return <RentalChrome path={path} alternate={alternate}><main><section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow">{city} · аренда транспорта</div><h1>{title}</h1><p>Сравните технику, тарифы на разные сроки и залог. Наличие на ваши даты и условия выдачи подтверждаем перед бронированием.</p><div className="hero-price"><strong>{minimum?price(minimum,'ru'):'По запросу'}</strong>{minimum&&<span>за 1 день · залог отдельно</span>}</div><div className="hero-actions"><a className="btn btn-primary" href="#models">Выбрать технику</a><a className="btn btn-secondary" href="#conditions">Условия аренды</a></div></div><div className="hero-media">{hero?.published_data?.photos[0]?<RentalPhoto src={hero.published_data.photos[0].src} alt={hero.published_data.translations.ru!.title} eager/>:<RentalPhoto src={cityPages.dalat.photos[0]} alt="Путешествия во Вьетнаме" eager/>}<div className="hero-badge"><b>{scope.length?scope.length+' позиций в каталоге':'Подбор транспорта'}</b><span>Доступность проверяем на ваши даты.</span></div></div></div></section>
 <section className="quick" aria-label="Навигация по странице"><div className="container quick-row">{quick.map(([id,label],i)=><a className="quick-chip" key={id} href={'#'+id}><i>{scope[i%Math.max(scope.length,1)]?.published_data?.photos[0]?<RentalPhoto src={scope[i%scope.length].published_data!.photos[0].src} alt=""/>:<span aria-hidden="true">{i+1}</span>}</i>{label}</a>)}</div></section>
 <section className="section" id="models"><div className="container"><div className="section-head"><div><div className="eyebrow">Каталог · {city}</div><h2>Выберите технику</h2></div><p>У каждой позиции свои тарифы, залог и номер в каталоге. Одинаковые модели могут относиться к разным единицам техники.</p></div>{filters}<nav className="filters" aria-label="Быстрые ценовые фильтры"><Link prefetch={false} className={'filter'+(!search.priceMin&&!search.priceMax?' active':'')} href={chip({})}>Все цены</Link><Link prefetch={false} className={'filter'+(search.priceMax==='170000'?' active':'')} href={chip({currency:'VND',unit:'day',priceMax:'170000'})}>До 170 000 VND / день</Link><Link prefetch={false} className={'filter'+(search.priceMin==='300000'?' active':'')} href={chip({currency:'VND',unit:'day',priceMin:'300000'})}>От 300 000 VND / день</Link></nav>{sortNotice&&<p role="status">Для сравнения и сортировки цен выберите одну валюту и один период.</p>}<p className="results-count" data-results={filtered.length} aria-live="polite">Найдено {filtered.length} позиций{pages>1?` · страница ${page} из ${pages}`:''}</p>{visible.length?<div className="rental-grid" id="rentalGrid">{visible.map(o=><RentalCard key={o.id} offering={o}/>)}</div>:<div className="catalog-empty"><h3>Предложения не найдены</h3><p>Измените фильтры или отправьте запрос на подбор.</p><Link className="btn btn-secondary" href={path+'#models'} prefetch={false}>Сбросить фильтры</Link></div>}{pages>1&&<nav className="pagination" aria-label="Страницы каталога">{pageLinks.map((href,i)=><Link prefetch={false} href={href+'#models'} key={href} aria-current={page===i+1?'page':undefined}>{i+1}</Link>)}</nav>}</div></section>
 <section className="section soft" id="conditions"><div className="container"><div className="section-head"><div><div className="eyebrow">Перед арендой</div><h2>Условия — без сюрпризов</h2></div><p>Уточняем условия выбранной модели до передачи техники. Тариф и залог показываются раздельно.</p></div><div className="rules-grid"><div className="rules-main"><h3>Что важно согласовать</h3><div className="rule-list">{[['Комплектация','Шлемы, замок, кофр и дополнительное оснащение подтверждаются для вашей модели.'],['Доставка','Проверим возможность, адрес, время и стоимость.'],['Срок аренды','Сравните опубликованные тарифы на день, неделю и месяц.'],['Залог','Сумма указана отдельно в карточке, условия возврата согласуются заранее.'],['Выдача и возврат','Уточним точку встречи, документы и состояние топлива.'],['Повреждения','Порядок осмотра, ответственность и условия ремонта согласуем до выдачи.']].map(([title,copy])=><div className="rule" key={title}><b>{title}</b><span>{copy}</span></div>)}</div></div><div className="rules-side"><div className="note"><h3>Документы</h3><p>Сообщите, какие водительские документы у вас есть. Организатор уточнит требования для выбранной техники.</p></div><div className="note orange"><h3>Выбираете впервые?</h3><p>Расскажите о своём опыте и планах. Поможем обсудить подходящую технику и формат поездки.</p></div></div></div></div></section>
 <section className="section" id="process"><div className="container"><div className="section-head"><div><div className="eyebrow">Как это работает</div><h2>От выбора до ключей — четыре шага</h2></div><p>Сначала выберите технику и даты, затем подтвердите конкретные условия.</p></div><div className="steps">{[['Выберите модель','Сравните тарифы, фотографии и залог.'],['Отправьте даты','Проверим наличие техники на срок аренды.'],['Подтвердите условия','Согласуем тариф, залог, документы и место выдачи.'],['Получите технику','Осмотрите её вместе с организатором перед поездкой.']].map(([title,copy],i)=><article className="step" key={title}><div className="step-num">0{i+1}</div><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
 <section className="section soft" id="team"><div className="container people"><div className="people-intro"><div className="eyebrow">{city}</div><h2>Поможем с арендой</h2><p>Подберём технику под срок поездки и уточним условия у организатора.</p></div><div className="person-grid"><article className="person"><div><div className="avatar" aria-hidden="true">TG</div><h3>Telegram</h3><p>Напишите @mototourvietnam: город, даты и пожелания к технике.</p></div><a className="btn btn-primary" href={contacts.telegramContact} target="_blank" rel="noopener noreferrer">Написать →</a></article><article className="person"><div><div className="avatar" aria-hidden="true">WA</div><h3>WhatsApp</h3><p>Удобный способ согласовать наличие, выдачу и возврат.</p></div><a className="btn btn-primary" href={contacts.whatsapp} target="_blank" rel="noopener noreferrer">Написать →</a></article></div></div></section>
 <section className="section dark" id="routes"><div className="container"><div className="section-head"><div><div className="eyebrow">Планы на поездку</div><h2>Куда поехать</h2></div><p>Посмотрите направления и опубликованные туры или обсудите свой маршрут.</p></div><div className="routes">{ideas.map(idea=><Link className="route" href={idea.href} prefetch={false} key={idea.title}><RentalPhoto src={idea.photo} alt={idea.title}/><div className="route-content"><h3>{idea.title}</h3><p>{idea.copy}</p></div></Link>)}</div></div></section>
 <section className="section" id="faq"><div className="container"><div className="section-head"><div><div className="eyebrow">FAQ</div><h2>Частые вопросы</h2></div><p>Основное перед подтверждением аренды.</p></div><div className="faq-list">{faq.map(([q,a])=><details className="faq" key={q}><summary>{q}</summary><div className="faq-answer">{a}</div></details>)}</div></div></section>
 <section className="final" id="contacts"><div className="container final-grid"><div><div className="eyebrow">Аренда · {city}</div><h2>Подберём технику под ваши даты</h2><p>Укажите срок и удобный контакт. Подтвердим наличие, тариф, залог и место получения до бронирования.</p><div className="contact-row"><a href={contacts.whatsapp}>WhatsApp</a><a href={contacts.telegramContact}>Telegram</a><a href={contacts.instagram}>Instagram</a>{selectedCity==='dalat'&&<a href={contacts.googleMaps}>Google Maps · Далат</a>}</div></div><RentalInquiryForm path={path} city={city} offers={scope.map(o=>({id:o.id,label:o.published_data!.translations.ru!.title+(o.published_data!.vehicle?.inventoryCode?' · '+o.published_data!.vehicle.inventoryCode:'')+(selectedCity?'':' · '+cityPages[o.destination_id]?.name)}))}/></div></section>
 </main></RentalChrome>;
}
