'use client';
import {useEffect} from 'react';
export function CityRuntime({city}:{city:string}){useEffect(()=>{
 const root=document.querySelector<HTMLElement>('.city-page');if(!root)return;
 const controller=new AbortController(),signal=controller.signal;
 const drawer=root.querySelector<HTMLElement>('#drawer')!,backdrop=root.querySelector<HTMLElement>('#backdrop')!,menu=root.querySelector<HTMLButtonElement>('#openMenu')!,header=root.querySelector<HTMLElement>('#siteHeader')!,toc=root.querySelector<HTMLElement>('#sideToc')!;
 const oldOverflow=document.body.style.overflow;let focusTimer:ReturnType<typeof setTimeout>|undefined;
 function setDrawer(open:boolean,restore=true){clearTimeout(focusTimer);drawer.classList.toggle('open',open);backdrop.classList.toggle('open',open);drawer.inert=!open;drawer.setAttribute('aria-hidden',String(!open));menu.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':oldOverflow;if(open){const ms=Math.max(...getComputedStyle(drawer).transitionDuration.split(',').map(v=>parseFloat(v)*1000));focusTimer=setTimeout(()=>{if(drawer.classList.contains('open'))drawer.querySelector<HTMLButtonElement>('#closeMenu')?.focus({preventScroll:true});},ms+50);}else if(restore)menu.focus({preventScroll:true});}
 menu.addEventListener('click',()=>setDrawer(true),{signal});root.querySelector('#closeMenu')!.addEventListener('click',()=>setDrawer(false),{signal});backdrop.addEventListener('click',()=>setDrawer(false),{signal});
 drawer.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setDrawer(false,false),{signal}));
 document.addEventListener('keydown',e=>{if(!drawer.classList.contains('open'))return;if(e.key==='Escape'){e.preventDefault();setDrawer(false);}if(e.key==='Tab'){const nodes=[...drawer.querySelectorAll<HTMLElement>('a[href],button')].filter(e=>e.getClientRects().length),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}},{signal});
 const scroll=()=>{header.classList.toggle('scrolled',scrollY>50);header.classList.toggle('over-content',(root.querySelector('.hero')?.getBoundingClientRect().bottom??0)<=72);toc.classList.toggle('show',scrollY>650);};window.addEventListener('scroll',scroll,{passive:true,signal});scroll();
 const rail=root.querySelector<HTMLElement>('#tourRail');for(const [id,dir]of [['tourPrev',-1],['tourNext',1]]as const)root.querySelector('#'+id)?.addEventListener('click',()=>{const card=rail?.querySelector('.tour-card');rail?.scrollBy({left:dir*((card?.getBoundingClientRect().width??330)+14),behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});},{signal});
 const tocLinks=[...toc.querySelectorAll<HTMLAnchorElement>('a')];const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)tocLinks.forEach(a=>{const active=a.hash==='#'+e.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});},{rootMargin:'-30% 0px -55% 0px'});tocLinks.forEach(a=>{const section=root.querySelector(a.hash);if(section)observer.observe(section);});
 root.dataset.cityReady='true';return()=>{delete root.dataset.cityReady;clearTimeout(focusTimer);controller.abort();observer.disconnect();document.body.style.overflow=oldOverflow;};
 },[city]);return null;}
