/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import {readFileSync} from 'node:fs';
import {publicOfferings,price,duration} from '@/lib/catalog';
import type {Offering} from '@/lib/catalog-types';
import {cityPages,cityHref} from '@/lib/city-pages';
import mediaData from '@/content/city-pages/media.json';
import contacts from '@/content/homepage-ru/contacts.json';
import {CityRuntime} from './CityRuntime';
import {CityInquiryForm} from './CityInquiryForm';
type Media={avif:string;webp:string;width:number;height:number};
const media=mediaData as Record<string,Media>;
const level=(value?:string|null)=>({easy:'Начинающим',medium:'Средний',advanced:'Опытным',hard:'Опытным'}[value??'']??'Уровень уточняется');
function short(text:string,max=170){if(text.length<=max)return text;return text.slice(0,max).replace(/\s+\S*$/,'')+'…';}
function Photo({src,alt,hero=false}:{src:string;alt:string;hero?:boolean}){const m=media[src];return m?<picture><source srcSet={m.avif} type="image/avif"/><img src={m.webp} width={m.width} height={m.height} alt={alt} loading={hero?'eager':'lazy'} fetchPriority={hero?'high':'auto'}/></picture>:<img src={src} alt={alt} loading={hero?'eager':'lazy'}/>;}
function Head({kicker,title,copy}:{kicker:string;title:string;copy:string}){return <div className="section-head reveal"><div><div className="kicker">{kicker}</div><h2>{title}</h2></div><p className="lead">{copy}</p></div>;}
function External({href,children,className}:{href:string;children:React.ReactNode;className?:string}){return <a href={href} className={className} target="_blank" rel="noopener noreferrer">{children}</a>;}
const anchors=[['tours','Туры'],['bikes','Техника'],['people','Команда'],['compare','Цены'],['route','Маршрут'],['other','Ещё активности'],['faq','FAQ']] as const;
function Header(){return <><header className="site-header" id="siteHeader"><div className="container header-inner"><Link className="header-chip brand" href="/ru">ENDURO <b>VIETNAM</b></Link><nav className="nav" aria-label="Навигация страницы">{anchors.filter(([id])=>!['compare','other'].includes(id)).map(([id,text])=><a className="header-chip" key={id} href={'#'+id}>{text}</a>)}</nav><div className="head-actions"><External className="header-chip ig" href={contacts.instagram}>Instagram</External><External className="header-chip wa" href={contacts.whatsapp}>WhatsApp</External><button className="header-chip menu" id="openMenu" type="button" aria-expanded="false" aria-controls="drawer">Меню</button></div></div></header>
 <div className="backdrop" id="backdrop"/><aside className="drawer" id="drawer" role="dialog" aria-modal="true" aria-label="Меню" aria-hidden="true" inert><div className="container"><div className="drawer-top"><Link className="brand" href="/ru">ENDURO <b>VIETNAM</b></Link><button className="drawer-close" id="closeMenu" type="button" aria-label="Закрыть меню">×</button></div><div className="drawer-grid"><div><h4>Города и направления</h4><div className="city-cloud">{Object.entries(cityPages).map(([id,c])=><a key={id} href={cityHref(id)}>{c.name}</a>)}</div></div><div><h4>На этой странице</h4><div className="drawer-links">{anchors.map(([id,text])=><a key={id} href={'#'+id}>{text}<span>→</span></a>)}</div></div><div className="drawer-cta"><strong>Подобрать поездку</strong><p>Укажите дату и опыт. Поможем выбрать длительность и программу.</p><a className="btn btn-orange" href="#contacts">Оставить запрос</a></div></div></div></aside></>;}
function TourCard({offering}:{offering:Offering}){const d=offering.published_data!,t=d.translations.ru!,src=d.photos[0]?.src;return <article className="tour-card" data-offering-id={offering.id}><div className="tour-photo">{src&&<Photo src={src} alt={d.photos[0].alt.ru??t.title}/>}<span className="tour-tag">{d.duration?.unit==='days'?'Многодневный мототур':'Эндуро-тур'}</span></div><div className="tour-body"><div className="tour-meta"><span>{duration(d,'ru')}</span><span>{level(d.level)}</span><span>Старт: {cityPages[offering.destination_id]?.name??offering.destination_id}</span></div><h3 className="tour-title">{t.title}</h3><p className="tour-copy">{short(t.description)}</p><div className="tour-bottom"><div className="tour-price"><strong>{price(d.commerce,'ru')}</strong></div><a className="text-link" href={d.routes.ru}>Подробнее →</a></div></div></article>;}
export async function CityPage({id,path}:{id:string;path:string}){
 const original=cityPages[id],c=path.includes('/destinations/')&&['dalat','nhatrang','danang','muine'].includes(id)?{...original,title:'Туры и активный отдых · '+original.name}:original,all=await publicOfferings('ru');
 const tours=all.filter(o=>o.type==='tour'&&(o.destination_id===id||o.published_data?.endDestinationId===id)).sort((a,b)=>{const da=a.published_data?.duration,db=b.published_data?.duration;return (da?.value??0)*(da?.unit==='days'?24:1)-(db?.value??0)*(db?.unit==='days'?24:1);});
 const rentals=all.filter(o=>o.type==='rental'&&o.destination_id===id);
 const photo=(index:number)=>c.photos[index%c.photos.length],rentHref='/ru/rentals/motorbikes?city='+id;
 const lowest=tours.filter(o=>o.published_data?.commerce.amountMinor!==null&&o.published_data?.commerce.currency==='USD').sort((a,b)=>a.published_data!.commerce.amountMinor!-b.published_data!.commerce.amountMinor!)[0];
 const faq=[{question:'Можно ли поехать без опыта?',answer:'Сообщите, если это первый выезд. Подберём подходящий формат и обсудим подготовку. Не каждая многодневная программа подходит новичку; уровень уточняется перед подтверждением.'},{question:'Где начинается маршрут?',answer:id==='muine'?'В опубликованном туре Далат — Муйне старт находится в Далате. Муйне — часть маршрута и его конечное направление. Место встречи уточняется при подтверждении.':'Город старта указан в карточке тура. Точное место встречи и время подтверждаются на выбранную дату; название направления может охватывать несколько районов.'},{question:'Что входит в стоимость?',answer:'Смотрите условия конкретной программы. До подтверждения уточните модель мотоцикла, экипировку, сопровождение, топливо, питание и проживание. Состав услуг может отличаться у короткого и многодневного тура.'},{question:'Как выбрать длительность и уровень?',answer:'Сравните варианты в таблице, затем сообщите свой опыт, количество участников и даты. Окончательный трек и сложность зависят от программы, погоды и подготовки группы.'},{question:'Чем тур отличается от аренды?',answer:'Тур — поездка по программе с согласованным сопровождением. Аренда — техника для самостоятельного маршрута и отдельный договор. Разделы и цены на странице разделены.'},{question:'Запрос сразу бронирует поездку?',answer:'Нет. Форма сохраняет запрос на подбор. Наличие техники, дату, окончательную стоимость и условия подтверждаем отдельно. Для оперативной связи доступны WhatsApp и Telegram.'}];
 const guides=[{title:'Как выбрать маршрут и длительность',copy:'Сравните опубликованные программы и город старта. Для многодневной поездки откройте полный маршрут.',href:'#compare',photo:photo(3)},{title:'Первый выезд: подготовка',copy:'Опыт, документы, одежда и условия программы — что уточнить перед подтверждением поездки.',href:'#preparation',photo:photo(1)},{title:'Тур или самостоятельная аренда',copy:rentals.length?'Посмотрите реальную технику в отдельном каталоге аренды. Цены аренды не являются ценами тура.':'Для тура обсудите модель и комплектацию. Самостоятельная аренда в этом направлении пока подбирается по запросу.',href:rentals.length?rentHref:'#bikes',photo:photo(2)}];
 const structured={'@context':'https://schema.org','@type':'CollectionPage',name:c.title,description:c.subtitle,hasPart:tours.map(o=>({'@type':'WebPage',name:o.published_data!.translations.ru!.title,url:o.published_data!.routes.ru}))};
 return <><style dangerouslySetInnerHTML={{__html:readFileSync('content/city-pages/styles.css','utf8')}}/><div className="city-page" data-city={id}><Header/><main>
 <section className="hero" id="top"><div className="hero-media"><Photo src={photo(0)} alt={c.title+' · фото маршрута Enduro Vietnam'} hero/></div><div className="container hero-inner"><div className="hero-copy"><div className="crumbs"><Link href="/ru">Главная</Link><span>·</span><Link href="/ru/destinations">Направления</Link><span>·</span><span>{c.name}</span></div><div className="kicker" style={{color:'#ff8a61'}}>{c.name} · {c.region}</div><h1>{c.title}</h1><p className="subtitle">{c.subtitle}</p><div className="hero-actions"><a className="btn btn-orange" href="#tours">Выбрать тур</a><a className="btn btn-light" href="#contacts">Подобрать по уровню</a></div><div className="hero-facts">{lowest&&<span>{price(lowest.published_data!.commerce,'ru')}</span>}<span>{tours.length} опубликованных программ</span><span>Уровень и дата по согласованию</span>{rentals.length>0&&<span>{rentals.length} позиций аренды отдельно</span>}</div></div></div></section>
 <section className="quick-index" aria-label="Быстрая навигация"><div className="container quick-row"><div className="quick-label">На странице</div><div className="quick-scroll">{anchors.map(([anchor,text],index)=><a className="quick-pill" href={'#'+anchor} key={anchor}><span className="quick-thumb"><Photo src={photo(index)} alt=""/></span>{text}</a>)}</div></div></section>
 <nav className="side-toc" id="sideToc" aria-label="Оглавление страницы"><small>Оглавление</small>{anchors.map(([anchor,text])=><a href={'#'+anchor} key={anchor}>{text}</a>)}</nav>
 <section className="section screenish" id="tours"><div className="container"><Head kicker="Выберите формат" title={c.title+'.'} copy="Сначала сравните длительность и программу, затем обсудите уровень и мотоцикл. Туры, самостоятельная аренда и будущие активности представлены отдельно."/><div className="tour-toolbar"><p className="small">{tours.length} опубликованных программ · детали и условия в карточках</p><div className="rail-controls"><button className="rail-btn" id="tourPrev" type="button" aria-label="Предыдущие туры">←</button><button className="rail-btn" id="tourNext" type="button" aria-label="Следующие туры">→</button></div></div>{tours.length?<div className="tour-rail reveal" id="tourRail">{tours.map(o=><TourCard key={o.id} offering={o}/>)}</div>:<div className="empty-offers">Опубликованных программ пока нет. <a href="#contacts">Запросить подбор →</a></div>}<a className="text-link" style={{display:'inline-block',marginTop:20}} href={'/ru/all-tours?city='+id}>Каталог туров этого направления →</a></div></section>
 <section className="section soft screenish" id="bikes"><div className="container"><Head kicker="Техника" title="На чём поедем." copy="Модель для тура, комплектацию и доступность подтверждаем на дату поездки. Для самостоятельного маршрута смотрите отдельные предложения аренды."/><div className="bikes-wrap reveal"><div className="bike-visual"><Photo src={photo(1)} alt={'Мотоциклы на маршруте · '+c.name}/><div className="bike-visual-copy"><h3>Байк под тур и райдера</h3><p>Важны опыт, маршрут и удобство управления. Условия техники для тура смотрите в программе; стоимость аренды не заменяет стоимость участия.</p></div></div><div>{rentals.length?<><div className="kicker">Самостоятельная аренда · {c.name}</div><div className="bike-list">{rentals.slice(0,6).map(o=>{const d=o.published_data!;return <div className="bike-row" data-rental-id={o.id} key={o.id}><div><h3>{d.vehicle?.model??d.translations.ru!.title}</h3><small>{d.vehicle?.inventoryCode??'Аренда отдельно от тура'}</small></div><div className="value">Самостоятельно</div><div className="price">{price(d.commerce,'ru')}</div><a href={d.routes.ru} aria-label={'Условия аренды '+d.translations.ru!.title}>→</a></div>;})}</div><a className="btn btn-dark" style={{marginTop:18}} href={rentHref}>Все {rentals.length} позиций аренды →</a></>:<div className="bike-list">{[['Модель мотоцикла','Подбирается по программе и опыту'],['Экипировка','Комплект уточняется до старта'],['Доступность','Проверяется на выбранную дату'],['Самостоятельная аренда','В этом направлении — по запросу']].map(([title,copy])=><div className="bike-row" key={title}><div><h3>{title}</h3><small>{copy}</small></div><div className="value">До подтверждения</div><div className="price">Уточнить</div><a href="#contacts" aria-label={'Уточнить: '+title}>→</a></div>)}</div>}<div className="bike-note"><b>Важно:</b> аренда и тур имеют разные условия. Уточните документы, депозит, страхование и доплаты до подтверждения.</div></div></div></div></section>
 <section className="section screenish" id="people"><div className="container"><div className="people-layout reveal"><div className="people-intro"><div className="kicker" style={{color:'#ff875f'}}>Команда · {c.name}</div><h2>Кто ведёт маршрут.</h2><p>Сообщите свой опыт до поездки. При подтверждении программы уточним, кто сопровождает группу, язык общения и подготовку перед стартом.</p><a className="btn btn-light" href="#contacts" style={{marginTop:22,alignSelf:'flex-start'}}>Сообщить свой уровень</a></div><div className="people-cards">{c.people?c.people.map(person=><article className="person-card" key={person.name}><Photo src={person.photo} alt={person.name+' · инструктор Enduro Vietnam'}/><div className="person-copy"><small>{person.role}</small><h3>{person.name}</h3><p>Инструктор Enduro Vietnam. Участие в вашей поездке уточняется при подтверждении даты.</p></div></article>):[2,3].map((index)=><article className="person-card" key={index}><Photo src={photo(index)} alt={'Участники на маршруте Enduro Vietnam · '+c.name}/><div className="person-copy"><small>Фото из архива маршрутов</small><h3>{index===2?'На маршруте':'Вместе с группой'}</h3><p>Сопровождение и язык гида уточняем для выбранной программы и даты.</p></div></article>)}</div></div></div></section>
 <section className="section soft" id="compare"><div className="container"><Head kicker="Цены и форматы" title="Сравнить туры за минуту." copy="Опубликованные цены, длительность и город старта собраны вместе. По ссылке в строке доступны полная программа и условия."/><div className="compare-wrap reveal"><table className="compare"><thead><tr>{['Тур','Длительность','Уровень','Старт','Стоимость'].map(t=><th scope="col" key={t}>{t}</th>)}</tr></thead><tbody>{tours.map(o=>{const d=o.published_data!;return <tr key={o.id} data-price-id={o.id}><td><a href={d.routes.ru}>{d.translations.ru!.title}</a></td><td>{duration(d,'ru')}</td><td>{level(d.level)}</td><td>{cityPages[o.destination_id]?.name??o.destination_id}</td><td className="price">{price(d.commerce,'ru')}</td></tr>;})}</tbody></table></div><p className="small" style={{marginTop:10}}>Цены взяты из опубликованного каталога. Если единица расчёта не указана, уточните её вместе с комплектацией; итоговую стоимость подтверждаем перед поездкой.</p></div></section>
 <section className="section screenish" id="route"><div className="container"><Head kicker="Маршрут и рельеф" title={c.landscape+'.'} copy={c.routeCopy}/><div className="route-bento reveal"><div className="route-main"><Photo src={photo(3)} alt={'Маршрут Enduro Vietnam · '+c.name}/><div className="route-main-copy"><div className="kicker" style={{color:'#ff8a61'}}>{c.region}</div><h3>{c.landscape}.</h3></div></div>{[['Подготовка','Обсудите опыт, управление мотоциклом и подходящий темп до старта.'],['Программа','Проверьте последовательность остановок и город начала тура.'],['Погода и рельеф','Точный трек и остановки уточняются с учётом условий на дату поездки.'],['Уровень группы','Сообщите опыт каждого участника: это помогает выбрать подходящую сложность.']].map(([title,copy],index)=><div className="route-tile" key={title}><span className="num">0{index+1}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div><div className="level-strip reveal">{[['EASY','Первый выезд','Начните с подбора программы и честно сообщите, если опыта пока нет.'],['PRO','Есть опыт','Уточните желаемый рельеф и интенсивность до подтверждения тура.']].map(([badge,title,copy])=><div className="level-box" key={badge}><div className="level-badge">{badge}</div><div><h3>{title}</h3><p>{copy}</p></div><a href="#contacts">Подобрать →</a></div>)}</div></div></section>
 <section className="section soft" id="preparation"><div className="container"><Head kicker="До старта" title="Что уточнить и подготовить." copy="Состав услуг зависит от выбранного тура. Проверьте детали программы до отправки запроса и окончательного подтверждения."/><div className="info-grid reveal"><div className="info-panel"><h3>Условия программы</h3><ul className="check-list">{['Модель мотоцикла и комплектация','Гид, язык общения и инструктаж','Защитное снаряжение','Топливо, питание и проживание','Доплаты и правила отмены'].map(t=><li key={t}>{t}</li>)}</ul></div><div className="info-panel"><h3>Перед поездкой</h3><ul className="check-list">{['Сообщить реальный опыт вождения','Уточнить необходимые документы','Подтвердить дату и наличие техники','Подобрать одежду и обувь под маршрут','Проверить итоговую цену и единицу расчёта'].map(t=><li key={t}>{t}</li>)}</ul></div></div></div></section>
 <section className="section" id="reviews"><div className="container"><div className="review-top reveal"><div><div className="kicker">Опыт гостей</div><h2>Посмотрите реальные отзывы.</h2></div>{id==='dalat'?<External className="google-badge" href={contacts.googleMaps}>Google Maps · Далат ↗</External>:<External className="google-badge" href={contacts.tripadvisor}>Отзывы о компании · Tripadvisor ↗</External>}</div><div className="reviews reveal">{[['Программа','Смотрите впечатления о конкретном маршруте, а не только общий рейтинг компании.'],['Подготовка','Обратите внимание на опыт райдеров и то, какую программу они выбрали.'],['Связь','Если остались вопросы об уровне и условиях — напишите нам до подтверждения.']].map(([title,copy])=><article className="review" key={title}><div className="stars">{title}</div><p>{copy}</p><footer><span>До выбора поездки</span><a href="#contacts">Уточнить →</a></footer></article>)}</div></div></section>
 <section className="section soft" id="other"><div className="container"><Head kicker="Другие планы" title={'Ещё чем заняться · '+c.name+'.'} copy="Дополнительные активности подбираем по запросу. Программа, доступность и стоимость подтверждаются отдельно; это не опубликованные предложения тура."/><div className="activity-bento reveal">{c.activities.map((activity,index)=><a className={'act-card'+(index===0?' large':'')} href="#contacts" key={activity}><Photo src={photo(index+2)} alt={'Природная остановка на маршруте · '+c.name}/><span className="act-pill">→</span><div className="act-copy"><small>Подбор по запросу</small><h3>{activity}</h3><p>Расскажите о своих планах.</p></div></a>)}<a className="act-card wide" href={rentals.length?rentHref:'#contacts'}><Photo src={rentals[0]?.published_data?.photos[0]?.src??photo(1)} alt={rentals.length?'Техника для самостоятельной аренды · '+c.name:'Мотоциклы на маршруте · '+c.name}/><span className="act-pill">→</span><div className="act-copy"><small>{rentals.length?'Самостоятельно':'По запросу'}</small><h3>Аренда мото и скутеров</h3><p>{rentals.length?'Отдельный каталог моделей и тарифов.':'Уточните возможность подбора техники.'}</p></div></a></div></div></section>
 <section className="section" id="faq"><div className="container faq-grid"><div className="reveal"><div className="kicker">FAQ</div><h2>Перед мотопоездкой.</h2><p className="lead" style={{marginTop:16}}>Короткие ответы про маршрут, опыт, технику и подтверждение поездки.</p></div><div className="faq-list reveal">{faq.map(({question,answer})=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>
 <section className="section soft" id="articles"><div className="container"><Head kicker="Полезно перед поездкой" title="Быстрые подсказки." copy="Переходы к программе, подготовке и технике на этой странице помогут выбрать следующий шаг."/><div className="article-grid reveal">{guides.map(g=><article className="article-card" key={g.title}><div className="article-img"><Photo src={g.photo} alt={'Маршрут Enduro Vietnam · '+c.name}/></div><div className="article-copy"><small>{c.name}</small><h3>{g.title}</h3><p>{g.copy}</p><a href={g.href}>Посмотреть →</a></div></article>)}</div></div></section>
 <section className="final" id="contacts"><div className="final-bg"><Photo src={photo(0)} alt=""/></div><div className="container final-inner"><div className="reveal"><div className="kicker" style={{color:'#ff8a61'}}>Подобрать тур · {c.name}</div><h2>Расскажите, как вы ездите. Остальное подберём.</h2><p>Дата, количество участников и реальный опыт — этого достаточно, чтобы начать подбор программы, уровня и мотоцикла.</p><div className="hero-actions"><External className="btn btn-light" href={contacts.whatsapp}>WhatsApp</External><External className="btn btn-outline" href={contacts.telegramContact}>Telegram</External></div></div><CityInquiryForm city={c.name} path={path}/></div></section>
 </main><footer className="footer"><div className="container"><div className="footer-grid"><div><Link href="/ru" className="brand" style={{padding:0,color:'#fff'}}>ENDURO <b>VIETNAM</b></Link><p style={{marginTop:12}}>Эндуро, мотопутешествия, активный отдых и аренда по Вьетнаму.</p></div><div><h4>{c.name}</h4><div className="footer-links">{anchors.slice(0,4).map(([anchor,text])=><a key={anchor} href={'#'+anchor}>{text}</a>)}</div></div><div><h4>Направления</h4><div className="footer-links">{Object.entries(cityPages).filter(([city])=>city!==id).map(([city,data])=><a key={city} href={cityHref(city)}>{data.name}</a>)}</div></div><div><h4>Связь</h4><div className="footer-links"><External href={contacts.whatsapp}>WhatsApp</External><External href={contacts.telegramContact}>Telegram</External><External href={contacts.telegramChannel}>Telegram-канал</External><External href={contacts.instagram}>Instagram</External><External href={contacts.youtube}>YouTube</External><External href={contacts.tiktok}>TikTok</External>{id==='dalat'&&<External href={contacts.googleMaps}>Google Maps · Далат</External>}<External href={contacts.tripadvisor}>Tripadvisor · компания</External><Link href="/privacy">Политика конфиденциальности</Link></div></div></div><div className="footer-bottom"><span>© Enduro Vietnam, {new Date().getFullYear()}</span><span>{c.name} · мотопутешествия</span></div></div></footer><div className="floating"><a className="float primary" href="#contacts" aria-label="Запросить подбор">Заявка</a><External className="float" href={contacts.whatsapp}>WA</External><External className="float" href={contacts.telegramContact}>TG</External></div><CityRuntime city={id}/></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replaceAll('<','\\u003c')}}/></>;
}
