'use client';
import Link from 'next/link';
import {useRef,useState} from 'react';
export function CityInquiryForm({city,path}:{city:string;path:string}){
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);const key=useRef<string|null>(null);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy||saved)return;const form=event.currentTarget;if(!form.reportValidity())return;const data=new FormData(form);key.current??=crypto.randomUUID();setBusy(true);setStatus('Сохраняем запрос…');try{const response=await fetch('/api/home-inquiries',{method:'POST',headers:{'content-type':'application/json','idempotency-key':key.current},body:JSON.stringify({name:data.get('name'),contact:data.get('contact'),city,date:data.get('date'),comment:['Опыт: '+data.get('experience'),data.get('comment')].filter(Boolean).join(' · '),consent:data.get('consent'),sourcePath:path})});const result=await response.json();if(!response.ok||!result.saved)throw new Error(result.error||'Не удалось сохранить запрос');setSaved(true);setStatus('Запрос сохранён. Для оперативного подтверждения даты напишите нам в WhatsApp или Telegram.');}catch(error){setStatus(error instanceof Error?error.message:'Не удалось сохранить запрос. Попробуйте ещё раз.');}finally{setBusy(false);}}
 return <form className="final-form reveal" onSubmit={submit} aria-label={'Подбор тура · '+city}><div className="form-grid">
 <div className="field"><label htmlFor="city-inquiry-name">Имя *</label><input id="city-inquiry-name" className="control" name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder="Как к вам обращаться"/></div>
 <div className="field"><label htmlFor="city-inquiry-contact">Контакт *</label><input id="city-inquiry-contact" className="control" name="contact" autoComplete="tel" required minLength={4} maxLength={200} placeholder="Телефон, @Telegram или email"/></div>
 <div className="field"><label htmlFor="city-inquiry-date">Дата</label><input id="city-inquiry-date" className="control" name="date" type="date"/></div>
 <div className="field"><label htmlFor="city-inquiry-experience">Опыт</label><select id="city-inquiry-experience" className="control" name="experience"><option>Первый раз</option><option>Есть небольшой опыт</option><option>Уверенно езжу</option><option>Опытный эндуро-райдер</option></select></div>
 <div className="field full"><label htmlFor="city-inquiry-comment">Комментарий</label><textarea id="city-inquiry-comment" className="control" name="comment" maxLength={1800} placeholder="Количество участников, длительность и пожелания"/></div></div>
 <label className="form-consent"><input name="consent" type="checkbox" value="on" required/><span>Согласен на обработку данных для ответа на запрос. <Link href="/privacy">Политика конфиденциальности</Link></span></label>
 <button className="btn btn-orange" style={{marginTop:12}} type="submit" disabled={busy||saved}>{saved?'Запрос сохранён':busy?'Сохраняем…':'Запросить вариант →'}</button><p className="form-status" role="status" aria-live="polite">{status}</p><p className="small" style={{marginTop:9}}>Это запрос на подбор. Дата, техника и условия подтверждаются после проверки.</p><noscript><p className="small">Для отправки формы включите JavaScript или напишите в мессенджер рядом.</p></noscript></form>;
}
